/** @typedef {{ word: string, clue: string, display?: string }} Entry */

/** Crossword-style entries used to generate spiral puzzles. */
/** @type {Entry[]} */
export const ENTRIES = [
  { word: "ACE", clue: "One-pip card" },
  { word: "ALE", clue: "Pub pint" },
  { word: "ANT", clue: "Picnic pest" },
  { word: "APE", clue: "Gorilla, for one" },
  { word: "ARC", clue: "Circle section" },
  { word: "ASH", clue: "Fireplace dust" },
  { word: "ASK", clue: "Pose a question" },
  { word: "AXE", clue: "Chopping tool" },
  { word: "BAT", clue: "Cave flier" },
  { word: "BAY", clue: "Coastal inlet" },
  { word: "BED", clue: "Place to sleep" },
  { word: "BEE", clue: "Honey maker" },
  { word: "BIO", clue: "Life story, briefly" },
  { word: "BIT", clue: "Tiny amount" },
  { word: "BOA", clue: "Feathery scarf" },
  { word: "BOW", clue: "Acknowledge applause" },
  { word: "BOX", clue: "Cardboard container" },
  { word: "BUD", clue: "Flower-to-be" },
  { word: "CAB", clue: "Taxi" },
  { word: "CAN", clue: "Tin container" },
  { word: "CAP", clue: "Bottle top" },
  { word: "CAR", clue: "Road vehicle" },
  { word: "CAT", clue: "Meowing pet" },
  { word: "COW", clue: "Milk source" },
  { word: "CRY", clue: "Shed tears" },
  { word: "CUP", clue: "Tea holder" },
  { word: "CUT", clue: "Use scissors" },
  { word: "DAD", clue: "Father, familiarly" },
  { word: "DAY", clue: "24 hours" },
  { word: "DEW", clue: "Morning moisture" },
  { word: "DIE", clue: "Cube with pips" },
  { word: "DIG", clue: "Use a shovel" },
  { word: "DIP", clue: "Salsa, for one" },
  { word: "DOG", clue: "Barking pet" },
  { word: "DOT", clue: "Speck" },
  { word: "DRY", clue: "Not wet" },
  { word: "DUE", clue: "Owed" },
  { word: "EAR", clue: "Hearing organ" },
  { word: "EAT", clue: "Have a meal" },
  { word: "EEL", clue: "Snakelike fish" },
  { word: "EGG", clue: "Omelet starter" },
  { word: "ELF", clue: "Santa's helper" },
  { word: "ELK", clue: "Antlered animal" },
  { word: "EMU", clue: "Flightless bird" },
  { word: "END", clue: "Conclusion" },
  { word: "ERA", clue: "Historic period" },
  { word: "EVE", clue: "Day before" },
  { word: "FAN", clue: "Ceiling cooler" },
  { word: "FAR", clue: "Distant" },
  { word: "FEW", clue: "Not many" },
  { word: "FIT", clue: "In good shape" },
  { word: "FIX", clue: "Repair" },
  { word: "FLY", clue: "Travel by air" },
  { word: "FOG", clue: "Thick mist" },
  { word: "FOX", clue: "Sly mammal" },
  { word: "FRY", clue: "Cook in oil" },
  { word: "FUN", clue: "Enjoyment" },
  { word: "GAP", clue: "Opening" },
  { word: "GAS", clue: "Car fuel" },
  { word: "GEL", clue: "Hair goo" },
  { word: "GEM", clue: "Precious stone" },
  { word: "GET", clue: "Obtain" },
  { word: "GIN", clue: "Clear liquor" },
  { word: "GNU", clue: "African antelope" },
  { word: "GUM", clue: "Chewing candy" },
  { word: "GUN", clue: "Firearm" },
  { word: "GUY", clue: "Fellow" },
  { word: "GYM", clue: "Workout place" },
  { word: "HAM", clue: "Easter meat" },
  { word: "HAT", clue: "Head covering" },
  { word: "HAY", clue: "Dried grass" },
  { word: "HEN", clue: "Egg layer" },
  { word: "HEX", clue: "Evil spell" },
  { word: "HID", clue: "Concealed" },
  { word: "HIP", clue: "Joint below the waist" },
  { word: "HOG", clue: "Greedy eater" },
  { word: "HOP", clue: "Short jump" },
  { word: "HOT", clue: "Very warm" },
  { word: "HOW", clue: "In what way" },
  { word: "HUE", clue: "Color tone" },
  { word: "HUG", clue: "Embrace" },
  { word: "HUM", clue: "Wordless tune" },
  { word: "ICE", clue: "Frozen water" },
  { word: "ICY", clue: "Covered in frost" },
  { word: "ILL", clue: "Unwell" },
  { word: "INK", clue: "Pen fluid" },
  { word: "INN", clue: "Roadside lodge" },
  { word: "ION", clue: "Charged particle" },
  { word: "IRK", clue: "Annoy" },
  { word: "IVY", clue: "Climbing vine" },
  { word: "JAM", clue: "Toast spread" },
  { word: "JAR", clue: "Glass container" },
  { word: "JAW", clue: "Mouth bone" },
  { word: "JET", clue: "Fast plane" },
  { word: "JOB", clue: "Paid work" },
  { word: "JOG", clue: "Slow run" },
  { word: "JOT", clue: "Write briefly" },
  { word: "JOY", clue: "Great happiness" },
  { word: "JUG", clue: "Pitcher" },
  { word: "KEG", clue: "Beer barrel" },
  { word: "KEY", clue: "Door opener" },
  { word: "KID", clue: "Young goat" },
  { word: "KIT", clue: "Set of tools" },
  { word: "LAB", clue: "Science room" },
  { word: "LAD", clue: "Young fellow" },
  { word: "LAP", clue: "Once around a track" },
  { word: "LAW", clue: "Legal rule" },
  { word: "LAX", clue: "Not strict" },
  { word: "LAY", clue: "Place down" },
  { word: "LED", clue: "Guided" },
  { word: "LEG", clue: "Chair support" },
  { word: "LET", clue: "Allow" },
  { word: "LID", clue: "Pot cover" },
  { word: "LIE", clue: "Untruth" },
  { word: "LIP", clue: "Mouth edge" },
  { word: "LIT", clue: "Illuminated" },
  { word: "LOG", clue: "Fallen tree section" },
  { word: "LOT", clue: "Parking area" },
  { word: "LOW", clue: "Not high" },
  { word: "MAD", clue: "Angry" },
  { word: "MAN", clue: "Adult male" },
  { word: "MAP", clue: "Road atlas page" },
  { word: "MAT", clue: "Doorstep rug" },
  { word: "MAY", clue: "Spring month" },
  { word: "MIX", clue: "Combine" },
  { word: "MOB", clue: "Unruly crowd" },
  { word: "MOP", clue: "Floor cleaner" },
  { word: "MUD", clue: "Wet dirt" },
  { word: "MUG", clue: "Coffee cup" },
  { word: "NAG", clue: "Complain persistently" },
  { word: "NAP", clue: "Short sleep" },
  { word: "NET", clue: "Tennis barrier" },
  { word: "NEW", clue: "Not old" },
  { word: "NIL", clue: "Nothing" },
  { word: "NIP", clue: "Small bite" },
  { word: "NOD", clue: "Head gesture of yes" },
  { word: "NOR", clue: "And not" },
  { word: "NOT", clue: "Negating word" },
  { word: "NUN", clue: "Convent resident" },
  { word: "NUT", clue: "Acorn, for one" },
  { word: "OAK", clue: "Sturdy tree" },
  { word: "OAR", clue: "Rowboat paddle" },
  { word: "OAT", clue: "Cereal grain" },
  { word: "ODD", clue: "Not even" },
  { word: "OIL", clue: "Salad dressing base" },
  { word: "OLD", clue: "Aged" },
  { word: "ONE", clue: "Smallest whole number" },
  { word: "ORB", clue: "Sphere" },
  { word: "ORE", clue: "Mine find" },
  { word: "OUR", clue: "Belonging to us" },
  { word: "OUT", clue: "Not in" },
  { word: "OWE", clue: "Be in debt" },
  { word: "OWL", clue: "Night bird" },
  { word: "OWN", clue: "Possess" },
  { word: "PAD", clue: "Writing tablet" },
  { word: "PAL", clue: "Buddy" },
  { word: "PAN", clue: "Frying vessel" },
  { word: "PAW", clue: "Animal foot" },
  { word: "PAY", clue: "Compensate" },
  { word: "PEA", clue: "Pod vegetable" },
  { word: "PEN", clue: "Writing tool" },
  { word: "PET", clue: "Household animal" },
  { word: "PIE", clue: "Baked dessert" },
  { word: "PIG", clue: "Farm animal" },
  { word: "PIN", clue: "Sewing fastener" },
  { word: "PIT", clue: "Cherry center" },
  { word: "PLY", clue: "Wood layer" },
  { word: "POD", clue: "Pea container" },
  { word: "POP", clue: "Dad, casually" },
  { word: "POT", clue: "Cooking vessel" },
  { word: "PRO", clue: "Expert" },
  { word: "PRY", clue: "Snoop" },
  { word: "PUB", clue: "British bar" },
  { word: "PUN", clue: "Wordplay joke" },
  { word: "PUP", clue: "Young dog" },
  { word: "RAG", clue: "Cleaning cloth" },
  { word: "RAM", clue: "Male sheep" },
  { word: "RAN", clue: "Sprinted" },
  { word: "RAP", clue: "Hip-hop music" },
  { word: "RAT", clue: "Shipboard rodent" },
  { word: "RAW", clue: "Uncooked" },
  { word: "RED", clue: "Stop-light color" },
  { word: "RIB", clue: "Chest bone" },
  { word: "RID", clue: "Get ___ of" },
  { word: "RIG", clue: "Oil platform" },
  { word: "RIM", clue: "Cup edge" },
  { word: "RIP", clue: "Tear" },
  { word: "ROB", clue: "Steal from" },
  { word: "ROD", clue: "Fishing pole" },
  { word: "ROE", clue: "Fish eggs" },
  { word: "ROT", clue: "Decay" },
  { word: "ROW", clue: "Use oars" },
  { word: "RUB", clue: "Massage" },
  { word: "RUG", clue: "Floor covering" },
  { word: "RUM", clue: "Pirate drink" },
  { word: "RUN", clue: "Move swiftly on foot" },
  { word: "RYE", clue: "Whiskey grain" },
  { word: "SAD", clue: "Unhappy" },
  { word: "SAG", clue: "Droop" },
  { word: "SAP", clue: "Maple fluid" },
  { word: "SAT", clue: "Took a chair" },
  { word: "SAW", clue: "Cutting tool" },
  { word: "SAY", clue: "Speak" },
  { word: "SEA", clue: "Ocean" },
  { word: "SET", clue: "Tennis unit" },
  { word: "SEW", clue: "Use a needle" },
  { word: "SHE", clue: "That woman" },
  { word: "SHY", clue: "Bashful" },
  { word: "SIN", clue: "Moral wrong" },
  { word: "SIP", clue: "Small drink" },
  { word: "SIR", clue: "Polite address" },
  { word: "SIT", clue: "Take a seat" },
  { word: "SIX", clue: "Half a dozen" },
  { word: "SKI", clue: "Snow runner" },
  { word: "SKY", clue: "Where clouds float" },
  { word: "SLY", clue: "Cunning" },
  { word: "SOP", clue: "Bread dunked in gravy" },
  { word: "SOW", clue: "Plant seeds" },
  { word: "SOY", clue: "___ sauce" },
  { word: "SPA", clue: "Spot for a massage" },
  { word: "SPY", clue: "Secret agent" },
  { word: "STY", clue: "Pigpen" },
  { word: "SUM", clue: "Arithmetic total" },
  { word: "SUN", clue: "Daytime star" },
  { word: "TAB", clue: "Bar bill" },
  { word: "TAD", clue: "Tiny bit" },
  { word: "TAG", clue: "Price sticker" },
  { word: "TAN", clue: "Beach glow" },
  { word: "TAP", clue: "Faucet" },
  { word: "TAR", clue: "Road surface goo" },
  { word: "TEA", clue: "Afternoon drink" },
  { word: "TEN", clue: "Half a score" },
  { word: "TIE", clue: "Necktie" },
  { word: "TIN", clue: "Metal for cans" },
  { word: "TIP", clue: "Gratuity" },
  { word: "TOE", clue: "Foot digit" },
  { word: "TON", clue: "2,000 pounds" },
  { word: "TOP", clue: "Highest point" },
  { word: "TOW", clue: "Pull a vehicle" },
  { word: "TOY", clue: "Plaything" },
  { word: "TRY", clue: "Attempt" },
  { word: "TUB", clue: "Bath vessel" },
  { word: "TUG", clue: "Pull hard" },
  { word: "TWO", clue: "Pair" },
  { word: "URN", clue: "Coffee vessel" },
  { word: "USE", clue: "Employ" },
  { word: "VAN", clue: "Moving truck" },
  { word: "VAT", clue: "Large tub" },
  { word: "VET", clue: "Animal doctor" },
  { word: "VOW", clue: "Solemn promise" },
  { word: "WAD", clue: "Bundle of bills" },
  { word: "WAG", clue: "Move a tail" },
  { word: "WAR", clue: "Armed conflict" },
  { word: "WAS", clue: "Existed" },
  { word: "WAX", clue: "Candle material" },
  { word: "WAY", clue: "Path" },
  { word: "WEB", clue: "Spider's creation" },
  { word: "WET", clue: "Soaked" },
  { word: "WHO", clue: "Which person" },
  { word: "WHY", clue: "For what reason" },
  { word: "WIG", clue: "False hair" },
  { word: "WIN", clue: "Come in first" },
  { word: "WIT", clue: "Clever humor" },
  { word: "WOE", clue: "Sorrow" },
  { word: "WOK", clue: "Stir-fry pan" },
  { word: "WON", clue: "Came in first" },
  { word: "WOO", clue: "Court romantically" },
  { word: "YAK", clue: "Tibetan ox" },
  { word: "YAM", clue: "Orange tuber" },
  { word: "YAP", clue: "Sharp bark" },
  { word: "YAW", clue: "Swerve off course" },
  { word: "YES", clue: "Affirmative" },
  { word: "YET", clue: "Up to now" },
  { word: "YEW", clue: "Evergreen tree" },
  { word: "ZIP", clue: "Fastener sound" },
  { word: "ZOO", clue: "Animal park" },
  { word: "ABLE", clue: "Capable" },
  { word: "ACHE", clue: "Dull pain" },
  { word: "ACID", clue: "pH below 7" },
  { word: "ACRE", clue: "Land measure" },
  { word: "AGED", clue: "Grown old" },
  { word: "AIDE", clue: "Assistant" },
  { word: "AIMS", clue: "Goals" },
  { word: "AKIN", clue: "Similar" },
  { word: "ALAS", clue: "Cry of woe" },
  { word: "ALLY", clue: "Partner in war" },
  { word: "ALSO", clue: "In addition" },
  { word: "ALTO", clue: "Choir voice" },
  { word: "AMID", clue: "In the middle of" },
  { word: "ANEW", clue: "Once more" },
  { word: "APEX", clue: "Peak" },
  { word: "APSE", clue: "Church recess" },
  { word: "ARCH", clue: "Curved doorway" },
  { word: "AREA", clue: "Region" },
  { word: "ARID", clue: "Very dry" },
  { word: "ARMY", clue: "Land forces" },
  { word: "AUNT", clue: "Parent's sister" },
  { word: "AVID", clue: "Eager" },
  { word: "AWAY", clue: "Not here" },
  { word: "AXLE", clue: "Wheel rod" },
  { word: "BAKE", clue: "Cook in an oven" },
  { word: "BALD", clue: "Hairless" },
  { word: "BALL", clue: "Spherical toy" },
  { word: "BAND", clue: "Music group" },
  { word: "BANG", clue: "Loud noise" },
  { word: "BARK", clue: "Tree covering" },
  { word: "BARN", clue: "Farm building" },
  { word: "BASE", clue: "Foundation" },
  { word: "BATH", clue: "Soak in a tub" },
  { word: "BEAM", clue: "Ray of light" },
  { word: "BEAN", clue: "Chili ingredient" },
  { word: "BEAR", clue: "Forest mammal" },
  { word: "BEAT", clue: "Defeat" },
  { word: "BEEN", clue: "Existed previously" },
  { word: "BELL", clue: "School ringer" },
  { word: "BELT", clue: "Waist strap" },
  { word: "BEND", clue: "Curve" },
  { word: "BEST", clue: "Finest" },
  { word: "BIAS", clue: "Prejudice" },
  { word: "BIKE", clue: "Two-wheeler" },
  { word: "BILE", clue: "Liver fluid" },
  { word: "BILL", clue: "Restaurant check" },
  { word: "BIND", clue: "Tie together" },
  { word: "BIRD", clue: "Feathered flyer" },
  { word: "BITE", clue: "Use teeth on" },
  { word: "BLOW", clue: "Gust of wind" },
  { word: "BLUE", clue: "Sky color" },
  { word: "BLUR", clue: "Fuzzy image" },
  { word: "BOAR", clue: "Wild pig" },
  { word: "BOAT", clue: "Watercraft" },
  { word: "BODY", clue: "Physical form" },
  { word: "BOIL", clue: "Heat to 212°F" },
  { word: "BOLD", clue: "Daring" },
  { word: "BOLT", clue: "Lightning flash" },
  { word: "BOND", clue: "Chemical link" },
  { word: "BONE", clue: "Skeleton part" },
  { word: "BOOK", clue: "Library item" },
  { word: "BOOM", clue: "Loud blast" },
  { word: "BOOT", clue: "Winter footwear" },
  { word: "BORE", clue: "Dull person" },
  { word: "BORN", clue: "Brought into life" },
  { word: "BOSS", clue: "Workplace chief" },
  { word: "BOTH", clue: "The two" },
  { word: "BOWL", clue: "Soup dish" },
  { word: "BRAG", clue: "Boast" },
  { word: "BRAN", clue: "Cereal husk" },
  { word: "BRAY", clue: "Donkey sound" },
  { word: "BREW", clue: "Make coffee" },
  { word: "BRIM", clue: "Hat edge" },
  { word: "BUCK", clue: "Male deer" },
  { word: "BULB", clue: "Light source" },
  { word: "BULL", clue: "Male cattle" },
  { word: "BUMP", clue: "Small collision" },
  { word: "BUNK", clue: "Stacked bed" },
  { word: "BURN", clue: "Be on fire" },
  { word: "BURY", clue: "Put underground" },
  { word: "BUSH", clue: "Low shrub" },
  { word: "BUSY", clue: "Occupied" },
  { word: "BYTE", clue: "Eight bits" },
  { word: "CAFE", clue: "Coffee shop" },
  { word: "CAGE", clue: "Zoo enclosure" },
  { word: "CAKE", clue: "Birthday dessert" },
  { word: "CALF", clue: "Young cow" },
  { word: "CALL", clue: "Phone" },
  { word: "CALM", clue: "Peaceful" },
  { word: "CAME", clue: "Arrived" },
  { word: "CAMP", clue: "Summer getaway" },
  { word: "CANE", clue: "Walking stick" },
  { word: "CAPE", clue: "Superhero wear" },
  { word: "CARD", clue: "Ace or king" },
  { word: "CARE", clue: "Concern" },
  { word: "CART", clue: "Grocery wagon" },
  { word: "CASE", clue: "Lawyer's assignment" },
  { word: "CASH", clue: "Paper money" },
  { word: "CAST", clue: "Actors in a play" },
  { word: "CAVE", clue: "Underground chamber" },
  { word: "CELL", clue: "Prison room" },
  { word: "CENT", clue: "Penny" },
  { word: "CHAP", clue: "Fellow" },
  { word: "CHAR", clue: "Burn slightly" },
  { word: "CHAT", clue: "Casual talk" },
  { word: "CHEF", clue: "Kitchen pro" },
  { word: "CHEW", clue: "Masticate" },
  { word: "CHIN", clue: "Below the mouth" },
  { word: "CHIP", clue: "Poker disk" },
  { word: "CHOP", clue: "Cut with an ax" },
  { word: "CITY", clue: "Urban area" },
  { word: "CLAM", clue: "Shellfish" },
  { word: "CLAP", clue: "Applaud" },
  { word: "CLAW", clue: "Cat nail" },
  { word: "CLAY", clue: "Potter's material" },
  { word: "CLIP", clue: "Hair fastener" },
  { word: "CLOD", clue: "Lump of earth" },
  { word: "CLOG", clue: "Block a drain" },
  { word: "CLUB", clue: "Golf stick" },
  { word: "CLUE", clue: "Detective's hint" },
  { word: "COAL", clue: "Black fuel" },
  { word: "COAT", clue: "Winter wear" },
  { word: "CODE", clue: "Secret writing" },
  { word: "COIL", clue: "Spiral of wire" },
  { word: "COIN", clue: "Metal money" },
  { word: "COKE", clue: "Soft drink" },
  { word: "COLD", clue: "Chilly" },
  { word: "COLT", clue: "Young horse" },
  { word: "COMA", clue: "Deep unconsciousness" },
  { word: "COMB", clue: "Hair untangler" },
  { word: "COME", clue: "Arrive" },
  { word: "CONE", clue: "Ice-cream holder" },
  { word: "COOK", clue: "Prepare food" },
  { word: "COOL", clue: "Moderately cold" },
  { word: "COPE", clue: "Manage" },
  { word: "CORD", clue: "Thick string" },
  { word: "CORE", clue: "Apple center" },
  { word: "CORK", clue: "Bottle stopper" },
  { word: "CORN", clue: "Yellow kernel crop" },
  { word: "COST", clue: "Price" },
  { word: "COZY", clue: "Snug" },
  { word: "CRAB", clue: "Sideways walker" },
  { word: "CREW", clue: "Ship's staff" },
  { word: "CRIB", clue: "Baby bed" },
  { word: "CROP", clue: "Farm harvest" },
  { word: "CROW", clue: "Black bird" },
  { word: "CUBE", clue: "Six-sided solid" },
  { word: "CURE", clue: "Remedy" },
  { word: "CURL", clue: "Spiral of hair" },
  { word: "CUTE", clue: "Adorable" },
  { word: "DALE", clue: "Valley" },
  { word: "DAME", clue: "British title" },
  { word: "DAMP", clue: "Slightly wet" },
  { word: "DARE", clue: "Challenge" },
  { word: "DARK", clue: "Without light" },
  { word: "DARN", clue: "Mend socks" },
  { word: "DART", clue: "Pub projectile" },
  { word: "DASH", clue: "Sprint" },
  { word: "DATA", clue: "Information" },
  { word: "DATE", clue: "Calendar day" },
  { word: "DAWN", clue: "Daybreak" },
  { word: "DEAL", clue: "Bargain" },
  { word: "DEAR", clue: "Beloved" },
  { word: "DEBT", clue: "Money owed" },
  { word: "DECK", clue: "Pack of cards" },
  { word: "DEED", clue: "Heroic act" },
  { word: "DEEM", clue: "Consider" },
  { word: "DEEP", clue: "Far down" },
  { word: "DEER", clue: "Antlered animal" },
  { word: "DEFT", clue: "Skillful" },
  { word: "DEFY", clue: "Resist openly" },
  { word: "DELI", clue: "Sandwich shop" },
  { word: "DEMO", clue: "Sample version" },
  { word: "DENY", clue: "Say it isn't so" },
  { word: "DESK", clue: "Writing table" },
  { word: "DIAL", clue: "Phone interface" },
  { word: "DICE", clue: "Gambling cubes" },
  { word: "DIET", clue: "Eating plan" },
  { word: "DIME", clue: "Ten cents" },
  { word: "DINE", clue: "Eat dinner" },
  { word: "DIRE", clue: "Dreadful" },
  { word: "DIRT", clue: "Soil" },
  { word: "DISC", clue: "Frisbee shape" },
  { word: "DISH", clue: "Plate of food" },
  { word: "DISK", clue: "Computer platter" },
  { word: "DIVE", clue: "Plunge into water" },
  { word: "DOCK", clue: "Boat landing" },
  { word: "DOLL", clue: "Child's toy figure" },
  { word: "DOME", clue: "Rounded roof" },
  { word: "DONE", clue: "Finished" },
  { word: "DOOM", clue: "Grim fate" },
  { word: "DOOR", clue: "Room entrance" },
  { word: "DOSE", clue: "Medicine amount" },
  { word: "DOTE", clue: "Be excessively fond" },
  { word: "DOWN", clue: "Toward the floor" },
  { word: "DOZE", clue: "Light sleep" },
  { word: "DRAB", clue: "Dull in color" },
  { word: "DRAG", clue: "Pull along" },
  { word: "DRAW", clue: "Sketch" },
  { word: "DREW", clue: "Sketched" },
  { word: "DRIP", clue: "Fall in drops" },
  { word: "DROP", clue: "Let fall" },
  { word: "DRUM", clue: "Percussion instrument" },
  { word: "DUAL", clue: "Twofold" },
  { word: "DUCK", clue: "Pond bird" },
  { word: "DUEL", clue: "Two-person fight" },
  { word: "DUET", clue: "Song for two" },
  { word: "DUKE", clue: "Noble title" },
  { word: "DULL", clue: "Boring" },
  { word: "DULY", clue: "Properly" },
  { word: "DUMB", clue: "Unable to speak" },
  { word: "DUMP", clue: "Discard pile" },
  { word: "DUNE", clue: "Sand hill" },
  { word: "DUSK", clue: "Evening twilight" },
  { word: "DUST", clue: "Household particles" },
  { word: "DUTY", clue: "Obligation" },
  { word: "EACH", clue: "Every one" },
  { word: "EARN", clue: "Make money" },
  { word: "EASE", clue: "Comfort" },
  { word: "EAST", clue: "Sunrise direction" },
  { word: "EASY", clue: "Not hard" },
  { word: "ECHO", clue: "Reflected sound" },
  { word: "EDGE", clue: "Border" },
  { word: "EDIT", clue: "Revise text" },
  { word: "EELY", clue: "Like a slippery fish" },
  { word: "ELSE", clue: "Otherwise" },
  { word: "ENVY", clue: "Jealous feeling" },
  { word: "EPIC", clue: "Grand tale" },
  { word: "ETCH", clue: "Engrave with acid" },
  { word: "EVEN", clue: "Divisible by two" },
  { word: "EVER", clue: "At any time" },
  { word: "EVIL", clue: "Wicked" },
  { word: "EXAM", clue: "Test" },
  { word: "EXIT", clue: "Way out" },
  { word: "FACE", clue: "Front of the head" },
  { word: "FACT", clue: "True statement" },
  { word: "FADE", clue: "Lose color" },
  { word: "FAIL", clue: "Not succeed" },
  { word: "FAIR", clue: "Just" },
  { word: "FAKE", clue: "Not genuine" },
  { word: "FALL", clue: "Autumn" },
  { word: "FAME", clue: "Celebrity" },
  { word: "FARE", clue: "Taxi charge" },
  { word: "FARM", clue: "Crop-growing land" },
  { word: "FAST", clue: "Speedy" },
  { word: "FATE", clue: "Destiny" },
  { word: "FAWN", clue: "Young deer" },
  { word: "FEAR", clue: "Fright" },
  { word: "FEAT", clue: "Impressive act" },
  { word: "FEED", clue: "Give food to" },
  { word: "FEEL", clue: "Sense by touch" },
  { word: "FEET", clue: "Lower limbs" },
  { word: "FELL", clue: "Chopped down" },
  { word: "FELT", clue: "Soft fabric" },
  { word: "FILE", clue: "Folder of papers" },
  { word: "FILL", clue: "Make full" },
  { word: "FILM", clue: "Movie" },
  { word: "FIND", clue: "Discover" },
  { word: "FINE", clue: "Traffic penalty" },
  { word: "FIRE", clue: "Flames" },
  { word: "FIRM", clue: "Solid" },
  { word: "FISH", clue: "Aquatic animal" },
  { word: "FIST", clue: "Clenched hand" },
  { word: "FIVE", clue: "High-five number" },
  { word: "FLAG", clue: "National banner" },
  { word: "FLAT", clue: "Apartment" },
  { word: "FLAW", clue: "Defect" },
  { word: "FLEA", clue: "Tiny jumper" },
  { word: "FLED", clue: "Ran away" },
  { word: "FLEE", clue: "Run away" },
  { word: "FLEW", clue: "Traveled by air" },
  { word: "FLEX", clue: "Bend a muscle" },
  { word: "FLIP", clue: "Turn over" },
  { word: "FLIT", clue: "Move lightly" },
  { word: "FLOW", clue: "Move like water" },
  { word: "FOAM", clue: "Soap bubbles" },
  { word: "FOIL", clue: "Kitchen wrap" },
  { word: "FOLD", clue: "Crease" },
  { word: "FOLK", clue: "People" },
  { word: "FOND", clue: "Affectionate" },
  { word: "FONT", clue: "Typeface" },
  { word: "FOOD", clue: "Edibles" },
  { word: "FOOL", clue: "Simpleton" },
  { word: "FOOT", clue: "Twelve inches" },
  { word: "FORD", clue: "Cross a stream" },
  { word: "FORK", clue: "Eating utensil" },
  { word: "FORM", clue: "Shape" },
  { word: "FORT", clue: "Military stronghold" },
  { word: "FOUL", clue: "Against the rules" },
  { word: "FOUR", clue: "Quad number" },
  { word: "FREE", clue: "Without cost" },
  { word: "FRET", clue: "Worry" },
  { word: "FROG", clue: "Pond hopper" },
  { word: "FROM", clue: "Starting at" },
  { word: "FUEL", clue: "Energy source" },
  { word: "FULL", clue: "At capacity" },
  { word: "FUME", clue: "Angry vapor" },
  { word: "FUND", clue: "Money reserve" },
  { word: "FURY", clue: "Rage" },
  { word: "FUSE", clue: "Electrical safety device" },
  { word: "FUSS", clue: "Commotion" },
  { word: "GAIN", clue: "Obtain" },
  { word: "GALA", clue: "Festive event" },
  { word: "GAME", clue: "Playful contest" },
  { word: "GAPE", clue: "Stare open-mouthed" },
  { word: "GASP", clue: "Catch one's breath" },
  { word: "GATE", clue: "Yard entrance" },
  { word: "GAZE", clue: "Steady look" },
  { word: "GEAR", clue: "Equipment" },
  { word: "GEMS", clue: "Jewels" },
  { word: "GERM", clue: "Microbe" },
  { word: "GIFT", clue: "Present" },
  { word: "GILD", clue: "Cover with gold" },
  { word: "GILL", clue: "Fish breather" },
  { word: "GILT", clue: "Gold covering" },
  { word: "GIRL", clue: "Young female" },
  { word: "GIST", clue: "Main point" },
  { word: "GIVE", clue: "Hand over" },
  { word: "GLAD", clue: "Happy" },
  { word: "GLEE", clue: "Delight" },
  { word: "GLEN", clue: "Narrow valley" },
  { word: "GLOW", clue: "Soft light" },
  { word: "GLUE", clue: "Adhesive" },
  { word: "GLUM", clue: "Morose" },
  { word: "GOAL", clue: "Soccer score" },
  { word: "GOAT", clue: "Bearded farm animal" },
  { word: "GOLD", clue: "Precious yellow metal" },
  { word: "GOLF", clue: "Club-and-ball sport" },
  { word: "GONE", clue: "No longer here" },
  { word: "GOOD", clue: "Satisfactory" },
  { word: "GOOF", clue: "Blunder" },
  { word: "GOSH", clue: "Mild exclamation" },
  { word: "GOUT", clue: "Joint ailment" },
  { word: "GOWN", clue: "Formal dress" },
  { word: "GRAB", clue: "Seize" },
  { word: "GRAM", clue: "Metric weight" },
  { word: "GRAY", clue: "Ash color" },
  { word: "GREW", clue: "Got bigger" },
  { word: "GREY", clue: "British ash color" },
  { word: "GRID", clue: "Network of lines" },
  { word: "GRIM", clue: "Stern" },
  { word: "GRIN", clue: "Broad smile" },
  { word: "GRIP", clue: "Firm hold" },
  { word: "GRIT", clue: "Courageous resolve" },
  { word: "GROW", clue: "Get bigger" },
  { word: "GRUB", clue: "Larva" },
  { word: "GULF", clue: "Large bay" },
  { word: "GULL", clue: "Seabird" },
  { word: "GULP", clue: "Swallow hard" },
  { word: "GURU", clue: "Spiritual teacher" },
  { word: "GUSH", clue: "Flow suddenly" },
  { word: "GUST", clue: "Sudden wind" },
  { word: "GYRO", clue: "Greek sandwich" },
  { word: "HACK", clue: "Chop roughly" },
  { word: "HAIL", clue: "Frozen rain" },
  { word: "HAIR", clue: "Head covering strands" },
  { word: "HALF", clue: "Fifty percent" },
  { word: "HALL", clue: "Corridor" },
  { word: "HALO", clue: "Angel's ring" },
  { word: "HALT", clue: "Stop" },
  { word: "HAND", clue: "Palm and fingers" },
  { word: "HANG", clue: "Suspend" },
  { word: "HARD", clue: "Not soft" },
  { word: "HARE", clue: "Rabbit relative" },
  { word: "HARM", clue: "Injury" },
  { word: "HARP", clue: "Stringed instrument" },
  { word: "HATE", clue: "Loathe" },
  { word: "HAUL", clue: "Transport" },
  { word: "HAVE", clue: "Possess" },
  { word: "HAWK", clue: "Bird of prey" },
  { word: "HAZE", clue: "Atmospheric blur" },
  { word: "HEAD", clue: "Body's top" },
  { word: "HEAL", clue: "Make well" },
  { word: "HEAP", clue: "Pile" },
  { word: "HEAR", clue: "Perceive sound" },
  { word: "HEAT", clue: "Warmth" },
  { word: "HEEL", clue: "Back of the foot" },
  { word: "HEIR", clue: "Inheritance receiver" },
  { word: "HELD", clue: "Grasped" },
  { word: "HELM", clue: "Ship's wheel" },
  { word: "HELP", clue: "Assist" },
  { word: "HERB", clue: "Basil or thyme" },
  { word: "HERD", clue: "Group of cattle" },
  { word: "HERE", clue: "In this place" },
  { word: "HERO", clue: "Brave person" },
  { word: "HERS", clue: "Belonging to her" },
  { word: "HIDE", clue: "Conceal" },
  { word: "HIGH", clue: "Elevated" },
  { word: "HIKE", clue: "Long walk" },
  { word: "HILL", clue: "Small mountain" },
  { word: "HILT", clue: "Sword handle" },
  { word: "HINT", clue: "Subtle clue" },
  { word: "HIRE", clue: "Employ" },
  { word: "HISS", clue: "Snake sound" },
  { word: "HIVE", clue: "Bee home" },
  { word: "HOAX", clue: "Deceptive trick" },
  { word: "HOBO", clue: "Wanderer" },
  { word: "HOLD", clue: "Grasp" },
  { word: "HOLE", clue: "Opening" },
  { word: "HOME", clue: "Residence" },
  { word: "HONE", clue: "Sharpen" },
  { word: "HOOD", clue: "Jacket head cover" },
  { word: "HOOK", clue: "Curved catcher" },
  { word: "HOOP", clue: "Basketball ring" },
  { word: "HOOT", clue: "Owl sound" },
  { word: "HOPE", clue: "Optimistic wish" },
  { word: "HORN", clue: "Car noisemaker" },
  { word: "HOSE", clue: "Garden water tube" },
  { word: "HOST", clue: "Party giver" },
  { word: "HOUR", clue: "Sixty minutes" },
  { word: "HOWL", clue: "Wolf cry" },
  { word: "HUGE", clue: "Enormous" },
  { word: "HULL", clue: "Ship's body" },
  { word: "HUMP", clue: "Camel feature" },
  { word: "HUNG", clue: "Suspended" },
  { word: "HUNK", clue: "Large piece" },
  { word: "HUNT", clue: "Seek game" },
  { word: "HURL", clue: "Throw hard" },
  { word: "HURT", clue: "Cause pain" },
  { word: "HUSH", clue: "Be quiet" },
  { word: "HYMN", clue: "Sacred song" },
  { word: "ICED", clue: "Covered with frost" },
  { word: "ICON", clue: "Revered symbol" },
  { word: "IDEA", clue: "Notion" },
  { word: "IDLE", clue: "Not busy" },
  { word: "IDOL", clue: "Adored figure" },
  { word: "IMPS", clue: "Little mischief-makers" },
  { word: "INFO", clue: "Data, briefly" },
  { word: "INTO", clue: "Toward the inside of" },
  { word: "IRIS", clue: "Eye part" },
  { word: "IRON", clue: "Fe on the periodic table" },
  { word: "ITCH", clue: "Urge to scratch" },
  { word: "ITEM", clue: "List entry" },
  { word: "JAZZ", clue: "Improvised music" },
  { word: "JEAN", clue: "Denim fabric" },
  { word: "JEEP", clue: "Rugged vehicle" },
  { word: "JEST", clue: "Joke" },
  { word: "JINX", clue: "Bad-luck charm" },
  { word: "JOIN", clue: "Connect" },
  { word: "JOKE", clue: "Funny story" },
  { word: "JOLT", clue: "Sudden shock" },
  { word: "JULY", clue: "Seventh month" },
  { word: "JUMP", clue: "Leap" },
  { word: "JUNE", clue: "Sixth month" },
  { word: "JUST", clue: "Fair" },
  { word: "KEEN", clue: "Eager" },
  { word: "KEEP", clue: "Retain" },
  { word: "KELP", clue: "Seaweed" },
  { word: "KEPT", clue: "Retained" },
  { word: "KICK", clue: "Strike with the foot" },
  { word: "KILN", clue: "Pottery oven" },
  { word: "KIND", clue: "Type" },
  { word: "KING", clue: "Chess piece" },
  { word: "KISS", clue: "Lip smack" },
  { word: "KITE", clue: "Wind-borne toy" },
  { word: "KNEE", clue: "Leg joint" },
  { word: "KNEW", clue: "Was aware of" },
  { word: "KNIT", clue: "Make a sweater" },
  { word: "KNOB", clue: "Door handle" },
  { word: "KNOT", clue: "Tied rope" },
  { word: "KNOW", clue: "Be aware of" },
  { word: "LACE", clue: "Shoe string" },
  { word: "LACK", clue: "Be without" },
  { word: "LADY", clue: "Woman" },
  { word: "LAID", clue: "Placed down" },
  { word: "LAIN", clue: "Rested flat" },
  { word: "LAIR", clue: "Den" },
  { word: "LAKE", clue: "Inland water" },
  { word: "LAMB", clue: "Young sheep" },
  { word: "LAME", clue: "Not convincing" },
  { word: "LAMP", clue: "Light source" },
  { word: "LAND", clue: "Come ashore" },
  { word: "LANE", clue: "Road division" },
  { word: "LARD", clue: "Cooking fat" },
  { word: "LARK", clue: "Songbird" },
  { word: "LASH", clue: "Whip stroke" },
  { word: "LAST", clue: "Final" },
  { word: "LATE", clue: "Tardy" },
  { word: "LAUD", clue: "Praise" },
  { word: "LAVA", clue: "Molten rock" },
  { word: "LAWN", clue: "Grass yard" },
  { word: "LAZY", clue: "Idle" },
  { word: "LEAD", clue: "Pb on the table" },
  { word: "LEAF", clue: "Tree flat" },
  { word: "LEAK", clue: "Unwanted drip" },
  { word: "LEAN", clue: "Not fatty" },
  { word: "LEAP", clue: "Jump" },
  { word: "LEFT", clue: "Opposite of right" },
  { word: "LEND", clue: "Let borrow" },
  { word: "LENS", clue: "Camera glass" },
  { word: "LESS", clue: "Not as much" },
  { word: "LIAR", clue: "Untruthful person" },
  { word: "LICK", clue: "Taste with the tongue" },
  { word: "LIDO", clue: "Public pool" },
  { word: "LIED", clue: "Told an untruth" },
  { word: "LIFE", clue: "Existence" },
  { word: "LIFT", clue: "Raise" },
  { word: "LIKE", clue: "Be fond of" },
  { word: "LILT", clue: "Cheerful rhythm" },
  { word: "LILY", clue: "Easter flower" },
  { word: "LIMB", clue: "Arm or leg" },
  { word: "LIME", clue: "Green citrus" },
  { word: "LINE", clue: "Queue" },
  { word: "LINK", clue: "Connection" },
  { word: "LINT", clue: "Dryer fluff" },
  { word: "LION", clue: "Pride member" },
  { word: "LIST", clue: "Series of items" },
  { word: "LIVE", clue: "Be alive" },
  { word: "LOAD", clue: "Cargo" },
  { word: "LOAF", clue: "Bread unit" },
  { word: "LOAN", clue: "Borrowed money" },
  { word: "LOCK", clue: "Door fastener" },
  { word: "LOFT", clue: "Attic space" },
  { word: "LOGO", clue: "Brand symbol" },
  { word: "LOIN", clue: "Cut of meat" },
  { word: "LONE", clue: "Solitary" },
  { word: "LONG", clue: "Not short" },
  { word: "LOOK", clue: "Glance" },
  { word: "LOOP", clue: "Circular path" },
  { word: "LORD", clue: "Nobleman" },
  { word: "LOSE", clue: "Suffer defeat" },
  { word: "LOSS", clue: "Defeat" },
  { word: "LOST", clue: "Misplaced" },
  { word: "LOUD", clue: "Noisy" },
  { word: "LOVE", clue: "Deep affection" },
  { word: "LUCK", clue: "Good fortune" },
  { word: "LUMP", clue: "Bump" },
  { word: "LUNG", clue: "Breathing organ" },
  { word: "LURE", clue: "Fishing bait" },
  { word: "LURK", clue: "Lie in wait" },
  { word: "LUSH", clue: "Luxuriant" },
  { word: "LYNX", clue: "Tufted-ear cat" },
  { word: "MADE", clue: "Created" },
  { word: "MAID", clue: "Hotel cleaner" },
  { word: "MAIL", clue: "Postal letters" },
  { word: "MAIN", clue: "Primary" },
  { word: "MAKE", clue: "Create" },
  { word: "MALE", clue: "Not female" },
  { word: "MALL", clue: "Shopping center" },
  { word: "MALT", clue: "Beer grain" },
  { word: "MANY", clue: "A lot of" },
  { word: "MARE", clue: "Female horse" },
  { word: "MARK", clue: "Spot" },
  { word: "MARS", clue: "Red planet" },
  { word: "MASK", clue: "Face cover" },
  { word: "MASS", clue: "Church service" },
  { word: "MAST", clue: "Ship's pole" },
  { word: "MATE", clue: "Partner" },
  { word: "MATH", clue: "Number subject" },
  { word: "MAZE", clue: "Labyrinth" },
  { word: "MEAL", clue: "Breakfast or dinner" },
  { word: "MEAN", clue: "Intend" },
  { word: "MEAT", clue: "Butchery product" },
  { word: "MEET", clue: "Encounter" },
  { word: "MELT", clue: "Turn to liquid" },
  { word: "MEMO", clue: "Office note" },
  { word: "MEND", clue: "Repair" },
  { word: "MENU", clue: "Restaurant list" },
  { word: "MERE", clue: "Nothing more than" },
  { word: "MESH", clue: "Interlock" },
  { word: "MESS", clue: "Untidy state" },
  { word: "MICE", clue: "Plural of mouse" },
  { word: "MILD", clue: "Gentle" },
  { word: "MILE", clue: "5,280 feet" },
  { word: "MILK", clue: "Dairy drink" },
  { word: "MILL", clue: "Grain grinder" },
  { word: "MIME", clue: "Silent actor" },
  { word: "MIND", clue: "Intellect" },
  { word: "MINE", clue: "Belonging to me" },
  { word: "MINI", clue: "Small version" },
  { word: "MINT", clue: "Spearmint plant" },
  { word: "MISS", clue: "Fail to hit" },
  { word: "MIST", clue: "Light fog" },
  { word: "MOAT", clue: "Castle water defense" },
  { word: "MOCK", clue: "Ridicule" },
  { word: "MODE", clue: "Manner" },
  { word: "MOLE", clue: "Garden digger" },
  { word: "MOLT", clue: "Shed feathers" },
  { word: "MONK", clue: "Monastery resident" },
  { word: "MOOD", clue: "Emotional state" },
  { word: "MOON", clue: "Earth's satellite" },
  { word: "MOOR", clue: "Open wasteland" },
  { word: "MORE", clue: "Additional" },
  { word: "MORN", clue: "Dawn time, poetically" },
  { word: "MOSS", clue: "Forest green cover" },
  { word: "MOST", clue: "Greatest amount" },
  { word: "MOTH", clue: "Night insect" },
  { word: "MOVE", clue: "Change position" },
  { word: "MUCH", clue: "A great deal" },
  { word: "MULE", clue: "Donkey-horse hybrid" },
  { word: "MUSE", clue: "Creative inspiration" },
  { word: "MUSH", clue: "Soft pulp" },
  { word: "MUST", clue: "Have to" },
  { word: "MUTE", clue: "Silent" },
  { word: "MUTT", clue: "Mixed-breed dog" },
  { word: "MYTH", clue: "Traditional tale" },
  { word: "NOTE", clue: "Musical tone" },
  { word: "NOVA", clue: "Exploding star" },
  { word: "OVEN", clue: "Baking chamber" },
  { word: "PAGE", clue: "Book leaf" },
  { word: "PEAS", clue: "Creatures in a pod" },
  { word: "PIPE", clue: "Tube" },
  { word: "PLUG", clue: "Electrical insert" },
  { word: "PUMP", clue: "Fluid mover" },
  { word: "RING", clue: "Circular band" },
  { word: "ROBE", clue: "Bath wrap" },
  { word: "ROPE", clue: "Thick cord" },
  { word: "RUBY", clue: "Red gem" },
  { word: "SAND", clue: "Beach grains" },
  { word: "SEAT", clue: "Assigned place" },
  { word: "SOAP", clue: "Cleanser" },
  { word: "SODA", clue: "Fizzy drink" },
  { word: "SONG", clue: "Musical piece" },
  { word: "SOUR", clue: "Tart" },
  { word: "STAR", clue: "Night-sky light" },
  { word: "SURF", clue: "Ride the waves" },
  { word: "TUNE", clue: "Melody" },
  { word: "WAVE", clue: "Ocean swell" },
  { word: "WIRE", clue: "Thin metal strand" },
  { word: "WOOD", clue: "Timber" },
  { word: "ABIDE", clue: "Tolerate" },
  { word: "ABOUT", clue: "Concerning" },
  { word: "ABOVE", clue: "Overhead" },
  { word: "ABUSE", clue: "Mistreat" },
  { word: "ABYSS", clue: "Bottomless pit" },
  { word: "ACTOR", clue: "Stage performer" },
  { word: "ACUTE", clue: "Sharply angled" },
  { word: "ADAPT", clue: "Adjust" },
  { word: "ADEPT", clue: "Skilled" },
  { word: "ADMIT", clue: "Confess" },
  { word: "ADOPT", clue: "Take as one's own" },
  { word: "ADORE", clue: "Love deeply" },
  { word: "ADULT", clue: "Grown-up" },
  { word: "AFTER", clue: "Following" },
  { word: "AGAIN", clue: "One more time" },
  { word: "AGENT", clue: "Representative" },
  { word: "AGILE", clue: "Nimble" },
  { word: "AGREE", clue: "Concur" },
  { word: "AHEAD", clue: "In front" },
  { word: "AISLE", clue: "Walkway between seats" },
  { word: "AKRON", clue: "Ohio's \"Rubber City\"" },
  { word: "ALARM", clue: "Warning signal" },
  { word: "ALBUM", clue: "Photo book" },
  { word: "ALERT", clue: "Warning" },
  { word: "ALIEN", clue: "Extraterrestrial" },
  { word: "ALIGN", clue: "Line up" },
  { word: "ALIKE", clue: "Similar" },
  { word: "ALIVE", clue: "Living" },
  { word: "ALLOW", clue: "Permit" },
  { word: "ALLOY", clue: "Metal mixture" },
  { word: "ALONE", clue: "By oneself" },
  { word: "ALONG", clue: "Beside" },
  { word: "ALOUD", clue: "Out loud" },
  { word: "ALPHA", clue: "First Greek letter" },
  { word: "ALTAR", clue: "Church table" },
  { word: "ALTER", clue: "Change" },
  { word: "AMBER", clue: "Fossil resin" },
  { word: "AMEND", clue: "Modify" },
  { word: "AMINO", clue: "___ acid" },
  { word: "AMONG", clue: "In the midst of" },
  { word: "AMPLE", clue: "Plenty" },
  { word: "AMUSE", clue: "Entertain" },
  { word: "ANGEL", clue: "Heavenly being" },
  { word: "ANGER", clue: "Rage" },
  { word: "ANGLE", clue: "Corner measure" },
  { word: "ANGRY", clue: "Mad" },
  { word: "ANKLE", clue: "Foot joint" },
  { word: "APART", clue: "Separated" },
  { word: "APPLE", clue: "Orchard fruit" },
  { word: "APPLY", clue: "Put to use" },
  { word: "APRIL", clue: "Fourth month" },
  { word: "APRON", clue: "Cook's wear" },
  { word: "ARENA", clue: "Sports venue" },
  { word: "ARGUE", clue: "Dispute" },
  { word: "ARISE", clue: "Get up" },
  { word: "ARMED", clue: "Carrying weapons" },
  { word: "ARMOR", clue: "Protective suit" },
  { word: "AROMA", clue: "Pleasant smell" },
  { word: "ARRAY", clue: "Ordered set" },
  { word: "ARROW", clue: "Bow projectile" },
  { word: "ARSON", clue: "Fire crime" },
  { word: "ASHES", clue: "Fire remains" },
  { word: "ASIDE", clue: "To one side" },
  { word: "ASSET", clue: "Valuable item" },
  { word: "ATLAS", clue: "Map book" },
  { word: "AUDIO", clue: "Sound-related" },
  { word: "AUDIT", clue: "Financial review" },
  { word: "AVOID", clue: "Stay away from" },
  { word: "AWAIT", clue: "Wait for" },
  { word: "AWAKE", clue: "Not asleep" },
  { word: "AWARD", clue: "Prize" },
  { word: "AWARE", clue: "Conscious of" },
  { word: "AWFUL", clue: "Terrible" },
  { word: "BACON", clue: "Breakfast meat" },
  { word: "BADGE", clue: "Pin of honor" },
  { word: "BADLY", clue: "Poorly" },
  { word: "BAGEL", clue: "Doughnut-shaped bread" },
  { word: "BAKED", clue: "Cooked in an oven" },
  { word: "BAKER", clue: "Bread maker" },
  { word: "BANJO", clue: "Five-string instrument" },
  { word: "BARGE", clue: "Flat boat" },
  { word: "BARON", clue: "Noble title" },
  { word: "BASIC", clue: "Fundamental" },
  { word: "BASIL", clue: "Pesto herb" },
  { word: "BATCH", clue: "Group produced together" },
  { word: "BATHE", clue: "Take a soak" },
  { word: "BEACH", clue: "Sandy shore" },
  { word: "BEANS", clue: "Chili ingredients" },
  { word: "BEARD", clue: "Facial hair" },
  { word: "BEAST", clue: "Wild animal" },
  { word: "BEGIN", clue: "Start" },
  { word: "BEING", clue: "Existence" },
  { word: "BELLE", clue: "Southern beauty" },
  { word: "BELLY", clue: "Stomach" },
  { word: "BELOW", clue: "Underneath" },
  { word: "BENCH", clue: "Park seat" },
  { word: "BERRY", clue: "Small fruit" },
  { word: "BIRTH", clue: "Delivery day" },
  { word: "BLACK", clue: "Coal color" },
  { word: "BLADE", clue: "Knife edge" },
  { word: "BLAME", clue: "Assign fault" },
  { word: "BLANK", clue: "Empty space" },
  { word: "BLAST", clue: "Explosion" },
  { word: "BLAZE", clue: "Fire" },
  { word: "BLEAK", clue: "Gloomy" },
  { word: "BLEED", clue: "Lose blood" },
  { word: "BLEND", clue: "Mix together" },
  { word: "BLESS", clue: "Give good wishes" },
  { word: "BLIND", clue: "Unable to see" },
  { word: "BLINK", clue: "Quick eye close" },
  { word: "BLISS", clue: "Perfect happiness" },
  { word: "BLOCK", clue: "Cube of wood" },
  { word: "BLOOD", clue: "Vein fluid" },
  { word: "BLOOM", clue: "Flower" },
  { word: "BLOWN", clue: "Moved by wind" },
  { word: "BOARD", clue: "Plank" },
  { word: "BOAST", clue: "Brag" },
  { word: "BOATS", clue: "Watercraft" },
  { word: "BONUS", clue: "Extra pay" },
  { word: "BOOST", clue: "Increase" },
  { word: "BOOTS", clue: "Footwear" },
  { word: "BOOZE", clue: "Alcohol, slang" },
  { word: "BORNE", clue: "Carried" },
  { word: "BOUND", clue: "Tied" },
  { word: "BOXER", clue: "Ring fighter" },
  { word: "BRACE", clue: "Support" },
  { word: "BRAID", clue: "Plaited hair" },
  { word: "BRAIN", clue: "Thinking organ" },
  { word: "BRAKE", clue: "Stopping device" },
  { word: "BRAND", clue: "Product label" },
  { word: "BRASS", clue: "Trumpet metal" },
  { word: "BRAVE", clue: "Courageous" },
  { word: "BREAD", clue: "Loaf product" },
  { word: "BREAK", clue: "Shatter" },
  { word: "BREED", clue: "Raise animals" },
  { word: "BRIBE", clue: "Illegal payment" },
  { word: "BRICK", clue: "Building block" },
  { word: "BRIDE", clue: "Wedding partner" },
  { word: "BRIEF", clue: "Short" },
  { word: "BRING", clue: "Carry along" },
  { word: "BRINK", clue: "Edge" },
  { word: "BRISK", clue: "Lively" },
  { word: "BROAD", clue: "Wide" },
  { word: "BROIL", clue: "Cook with direct heat" },
  { word: "BROKE", clue: "Out of money" },
  { word: "BROOK", clue: "Small stream" },
  { word: "BROOM", clue: "Sweeping tool" },
  { word: "BROTH", clue: "Clear soup" },
  { word: "BROWN", clue: "Coffee color" },
  { word: "BRUSH", clue: "Hair tool" },
  { word: "BUILD", clue: "Construct" },
  { word: "BUILT", clue: "Constructed" },
  { word: "BULGE", clue: "Swelling" },
  { word: "BULKY", clue: "Large and awkward" },
  { word: "BULLY", clue: "Intimidator" },
  { word: "BUMPY", clue: "Uneven" },
  { word: "BUNCH", clue: "Cluster" },
  { word: "BURNT", clue: "Charred" },
  { word: "BURST", clue: "Explode" },
  { word: "CABIN", clue: "Log home" },
  { word: "CABLE", clue: "Thick wire" },
  { word: "CACHE", clue: "Hidden store" },
  { word: "CACTI", clue: "Desert plants" },
  { word: "CADET", clue: "Military student" },
  { word: "CAGEY", clue: "Shrewd" },
  { word: "CAIRN", clue: "Stone pile marker" },
  { word: "CAMEL", clue: "Desert animal" },
  { word: "CAMEO", clue: "Brief role" },
  { word: "CAMPY", clue: "Amusingly exaggerated" },
  { word: "CANAL", clue: "Artificial waterway" },
  { word: "CANDY", clue: "Sweet treat" },
  { word: "CANOE", clue: "Paddle boat" },
  { word: "CANON", clue: "Official list" },
  { word: "CARGO", clue: "Freight" },
  { word: "CAROL", clue: "Christmas song" },
  { word: "CARRY", clue: "Transport" },
  { word: "CARVE", clue: "Cut into shape" },
  { word: "CATCH", clue: "Capture" },
  { word: "CAUSE", clue: "Reason" },
  { word: "CAVES", clue: "Underground chambers" },
  { word: "CEASE", clue: "Stop" },
  { word: "CEDAR", clue: "Aromatic wood" },
  { word: "CERES", clue: "Largest known asteroid" },
  { word: "CHAFE", clue: "Rub sore" },
  { word: "CHAIN", clue: "Linked metal rings" },
  { word: "CHAIR", clue: "Seat with a back" },
  { word: "CHALK", clue: "Blackboard stick" },
  { word: "CHAOS", clue: "Total disorder" },
  { word: "CHARM", clue: "Delightful quality" },
  { word: "CHART", clue: "Graph" },
  { word: "CHASE", clue: "Pursue" },
  { word: "CHEAP", clue: "Inexpensive" },
  { word: "CHEAT", clue: "Act dishonestly" },
  { word: "CHECK", clue: "Restaurant bill" },
  { word: "CHEEK", clue: "Side of the face" },
  { word: "CHEER", clue: "Show support" },
  { word: "CHESS", clue: "Board game with kings" },
  { word: "CHEST", clue: "Torso" },
  { word: "CHEWY", clue: "Requiring mastication" },
  { word: "CHICK", clue: "Baby bird" },
  { word: "CHIEF", clue: "Leader" },
  { word: "CHILD", clue: "Youngster" },
  { word: "CHILL", clue: "Coldness" },
  { word: "CHIME", clue: "Bell sound" },
  { word: "CHINA", clue: "Porcelain ware" },
  { word: "CHOIR", clue: "Singing group" },
  { word: "CHOKE", clue: "Gag" },
  { word: "CHORD", clue: "Musical tones together" },
  { word: "CHORE", clue: "Household task" },
  { word: "CHOSE", clue: "Picked" },
  { word: "CHUNK", clue: "Thick piece" },
  { word: "CHURN", clue: "Butter maker" },
  { word: "CIDER", clue: "Apple drink" },
  { word: "CIGAR", clue: "Rolled tobacco" },
  { word: "CINCH", clue: "Easy task" },
  { word: "CIVIC", clue: "Municipal" },
  { word: "CIVIL", clue: "Polite" },
  { word: "CLAIM", clue: "Assert ownership" },
  { word: "CLAMP", clue: "Holding tool" },
  { word: "CLANG", clue: "Metallic ring" },
  { word: "CLASH", clue: "Conflict" },
  { word: "CLASP", clue: "Fastener" },
  { word: "CLASS", clue: "School group" },
  { word: "CLEAN", clue: "Not dirty" },
  { word: "CLEAR", clue: "Transparent" },
  { word: "CLERK", clue: "Office worker" },
  { word: "CLICK", clue: "Mouse sound" },
  { word: "CLIFF", clue: "Steep rock face" },
  { word: "CLIMB", clue: "Go upward" },
  { word: "CLING", clue: "Hold tight" },
  { word: "CLIPS", clue: "Hair fasteners" },
  { word: "CLOCK", clue: "Timepiece" },
  { word: "CLONE", clue: "Genetic copy" },
  { word: "CLOSE", clue: "Shut" },
  { word: "CLOTH", clue: "Fabric" },
  { word: "CLOUD", clue: "Sky fluff" },
  { word: "CLOWN", clue: "Circus comic" },
  { word: "CLUES", clue: "Hints" },
  { word: "COAST", clue: "Shoreline" },
  { word: "COBRA", clue: "Hooded snake" },
  { word: "COCOA", clue: "Chocolate drink" },
  { word: "COLON", clue: "Punctuation mark" },
  { word: "COLOR", clue: "Hue" },
  { word: "COMET", clue: "Tailed sky object" },
  { word: "COMIC", clue: "Funny person" },
  { word: "COMMA", clue: "Pause punctuation" },
  { word: "CONCH", clue: "Spiral shell" },
  { word: "CORAL", clue: "Reef material" },
  { word: "CORDS", clue: "Strings" },
  { word: "COUCH", clue: "Sofa" },
  { word: "COUGH", clue: "Throat spasm" },
  { word: "COULD", clue: "Was able to" },
  { word: "COUNT", clue: "Tally" },
  { word: "COURT", clue: "Tennis venue" },
  { word: "COVER", clue: "Lid" },
  { word: "CRACK", clue: "Narrow break" },
  { word: "CRAFT", clue: "Handmade skill" },
  { word: "CRAMP", clue: "Muscle spasm" },
  { word: "CRANE", clue: "Construction bird" },
  { word: "CRANK", clue: "Grouchy person" },
  { word: "CRASH", clue: "Collision" },
  { word: "CRASS", clue: "Tasteless" },
  { word: "CRATE", clue: "Shipping box" },
  { word: "CRAVE", clue: "Desire strongly" },
  { word: "CRAWL", clue: "Move on hands and knees" },
  { word: "CRAZE", clue: "Fad" },
  { word: "CRAZY", clue: "Insane" },
  { word: "CREAK", clue: "Door sound" },
  { word: "CREAM", clue: "Milk fat" },
  { word: "CREDO", clue: "Belief statement" },
  { word: "CREED", clue: "System of beliefs" },
  { word: "CREEK", clue: "Small stream" },
  { word: "CREEP", clue: "Move stealthily" },
  { word: "CREME", clue: "French cream" },
  { word: "CREPE", clue: "Thin pancake" },
  { word: "CREPT", clue: "Moved stealthily" },
  { word: "CREST", clue: "Wave top" },
  { word: "CRIME", clue: "Illegal act" },
  { word: "CRISP", clue: "Crunchy" },
  { word: "CROOK", clue: "Criminal" },
  { word: "CROPS", clue: "Harvests" },
  { word: "CROSS", clue: "Intersection" },
  { word: "CROWD", clue: "Large group" },
  { word: "CROWN", clue: "Royal headwear" },
  { word: "CRUDE", clue: "Unrefined" },
  { word: "CRUEL", clue: "Harsh" },
  { word: "CRUMB", clue: "Bread bit" },
  { word: "CRUSH", clue: "Squeeze hard" },
  { word: "CRUST", clue: "Pie shell" },
  { word: "CRYPT", clue: "Underground tomb" },
  { word: "CUBIC", clue: "Cube-shaped" },
  { word: "CURRY", clue: "Spiced dish" },
  { word: "CURSE", clue: "Evil hex" },
  { word: "CURVE", clue: "Bend" },
  { word: "CYCLE", clue: "Bike" },
  { word: "DAILY", clue: "Every day" },
  { word: "DAIRY", clue: "Milk products" },
  { word: "DAISY", clue: "White petal flower" },
  { word: "DANCE", clue: "Move to music" },
  { word: "DANDY", clue: "Foppish fellow" },
  { word: "DEALT", clue: "Distributed cards" },
  { word: "DEATH", clue: "End of life" },
  { word: "DEBIT", clue: "Account charge" },
  { word: "DEBUG", clue: "Fix code" },
  { word: "DEBUT", clue: "First appearance" },
  { word: "DECAY", clue: "Rot" },
  { word: "DECOR", clue: "Interior style" },
  { word: "DECOY", clue: "Lure" },
  { word: "DELAY", clue: "Postpone" },
  { word: "DELTA", clue: "River mouth land" },
  { word: "DELVE", clue: "Dig deep" },
  { word: "DEMON", clue: "Evil spirit" },
  { word: "DENIM", clue: "Jeans fabric" },
  { word: "DENSE", clue: "Thick" },
  { word: "DEPOT", clue: "Storage station" },
  { word: "DEPTH", clue: "How deep" },
  { word: "DERBY", clue: "Horse race" },
  { word: "DEREK", clue: "Baseball's Jeter" },
  { word: "DETER", clue: "Discourage" },
  { word: "DIARY", clue: "Personal journal" },
  { word: "DICEY", clue: "Risky" },
  { word: "DIGIT", clue: "Numeral" },
  { word: "DINER", clue: "Casual restaurant" },
  { word: "DINGO", clue: "Australian wild dog" },
  { word: "DIRTY", clue: "Not clean" },
  { word: "DISCO", clue: "1970s dance music" },
  { word: "DITCH", clue: "Roadside trench" },
  { word: "DITTO", clue: "Same as above" },
  { word: "DIZZY", clue: "Lightheaded" },
  { word: "DODGE", clue: "Avoid by moving" },
  { word: "DOING", clue: "Action in progress" },
  { word: "DONOR", clue: "Gift giver" },
  { word: "DONUT", clue: "Fried ring pastry" },
  { word: "DOPEY", clue: "Slow-witted" },
  { word: "DOUBT", clue: "Uncertainty" },
  { word: "DOUGH", clue: "Bread mix" },
  { word: "DOUSE", clue: "Drench" },
  { word: "DOZEN", clue: "Twelve" },
  { word: "DRAFT", clue: "Preliminary version" },
  { word: "DRAIN", clue: "Empty liquid from" },
  { word: "DRAKE", clue: "Male duck" },
  { word: "DRAMA", clue: "Stage play" },
  { word: "DRANK", clue: "Consumed liquid" },
  { word: "DRAPE", clue: "Curtain" },
  { word: "DRAWL", clue: "Slow speech" },
  { word: "DRAWN", clue: "Sketched" },
  { word: "DREAD", clue: "Great fear" },
  { word: "DREAM", clue: "Sleep vision" },
  { word: "DRESS", clue: "Garment" },
  { word: "DRIED", clue: "Dehydrated" },
  { word: "DRIFT", clue: "Float along" },
  { word: "DRILL", clue: "Boring tool" },
  { word: "DRINK", clue: "Beverage" },
  { word: "DRIVE", clue: "Operate a car" },
  { word: "DRONE", clue: "Pilotless aircraft" },
  { word: "DROOL", clue: "Salivate" },
  { word: "DROOP", clue: "Sag" },
  { word: "DROVE", clue: "Operated a car" },
  { word: "DROWN", clue: "Die underwater" },
  { word: "DRUID", clue: "Celtic priest" },
  { word: "DRUNK", clue: "Intoxicated" },
  { word: "DRYER", clue: "Laundry machine" },
  { word: "DRYLY", clue: "With ironic tone" },
  { word: "DUCHY", clue: "Duke's territory" },
  { word: "DUMMY", clue: "Mannequin" },
  { word: "DUMPY", clue: "Short and stout" },
  { word: "DUNCE", clue: "Slow learner" },
  { word: "DUSKY", clue: "Dimly lit" },
  { word: "DUSTY", clue: "Covered in particles" },
  { word: "DUTCH", clue: "From the Netherlands" },
  { word: "DWARF", clue: "Snow White companion" },
  { word: "DWELL", clue: "Reside" },
  { word: "DYING", clue: "Near death" },
  { word: "EAGER", clue: "Enthusiastic" },
  { word: "EAGLE", clue: "National bird" },
  { word: "EARLY", clue: "Before the usual time" },
  { word: "EARTH", clue: "Our planet" },
  { word: "EASEL", clue: "Painter's stand" },
  { word: "EATEN", clue: "Consumed" },
  { word: "EATER", clue: "One who consumes" },
  { word: "EBONY", clue: "Dark hardwood" },
  { word: "EDSEL", clue: "Unsuccessful Ford offering" },
  { word: "EERIE", clue: "Strange and spooky" },
  { word: "EFREM", clue: "Zimbalist, Sr. or Jr." },
  { word: "EIGHT", clue: "Octet number" },
  { word: "ELATE", clue: "Make joyful" },
  { word: "ELBOW", clue: "Arm joint" },
  { word: "ELDER", clue: "Older person" },
  { word: "ELECT", clue: "Vote into office" },
  { word: "ELITE", clue: "Best of the best" },
  { word: "ELOPE", clue: "Run away to marry" },
  { word: "ELUDE", clue: "Escape from" },
  { word: "EMAIL", clue: "Digital message" },
  { word: "EMBED", clue: "Fix firmly" },
  { word: "EMBER", clue: "Glowing coal" },
  { word: "EMERY", clue: "Abrasive board" },
  { word: "EMPTY", clue: "Containing nothing" },
  { word: "ENACT", clue: "Make into law" },
  { word: "ENDOW", clue: "Provide with funds" },
  { word: "ENEMY", clue: "Foe" },
  { word: "ENJOY", clue: "Take pleasure in" },
  { word: "ENTER", clue: "Go in" },
  { word: "ENTRY", clue: "Doorway" },
  { word: "ENVOY", clue: "Diplomatic messenger" },
  { word: "EPOCH", clue: "Notable period" },
  { word: "EQUAL", clue: "The same" },
  { word: "EQUIP", clue: "Provide gear" },
  { word: "ERASE", clue: "Rub out" },
  { word: "ERECT", clue: "Upright" },
  { word: "ERROR", clue: "Mistake" },
  { word: "ERUPT", clue: "Burst forth" },
  { word: "ESSAY", clue: "School composition" },
  { word: "ETHER", clue: "Old anesthetic" },
  { word: "ETHIC", clue: "Moral principle" },
  { word: "EVADE", clue: "Dodge" },
  { word: "EVENT", clue: "Occurrence" },
  { word: "EVERY", clue: "Each" },
  { word: "EXACT", clue: "Precise" },
  { word: "EXALT", clue: "Praise highly" },
  { word: "EXCEL", clue: "Be outstanding" },
  { word: "EXERT", clue: "Apply force" },
  { word: "EXILE", clue: "Banishment" },
  { word: "EXIST", clue: "Be real" },
  { word: "EXTRA", clue: "Additional" },
  { word: "EXULT", clue: "Rejoice" },
  { word: "FABLE", clue: "Moral tale" },
  { word: "FACET", clue: "Aspect" },
  { word: "FADED", clue: "Lost color" },
  { word: "FAILS", clue: "Does not succeed" },
  { word: "FAINT", clue: "Barely perceptible" },
  { word: "FAIRY", clue: "Winged folklore being" },
  { word: "FAITH", clue: "Belief" },
  { word: "FALSE", clue: "Not true" },
  { word: "FANCY", clue: "Elaborate" },
  { word: "FARCE", clue: "Absurd comedy" },
  { word: "FATAL", clue: "Deadly" },
  { word: "FAULT", clue: "Blame" },
  { word: "FAUNA", clue: "Animal life" },
  { word: "FAVOR", clue: "Kind act" },
  { word: "FEAST", clue: "Large meal" },
  { word: "FEIGN", clue: "Pretend" },
  { word: "FELON", clue: "Serious criminal" },
  { word: "FEMUR", clue: "Thigh bone" },
  { word: "FENCE", clue: "Yard barrier" },
  { word: "FERAL", clue: "Wild" },
  { word: "FERRY", clue: "Water shuttle" },
  { word: "FETCH", clue: "Go get" },
  { word: "FEVER", clue: "High temperature" },
  { word: "FEWER", clue: "Not as many" },
  { word: "FIBER", clue: "Dietary roughage" },
  { word: "FIELD", clue: "Open grassy area" },
  { word: "FIEND", clue: "Evil person" },
  { word: "FIERY", clue: "Flaming" },
  { word: "FIFTH", clue: "After fourth" },
  { word: "FIFTY", clue: "Half a hundred" },
  { word: "FIGHT", clue: "Battle" },
  { word: "FILLY", clue: "Young female horse" },
  { word: "FINAL", clue: "Last" },
  { word: "FINCH", clue: "Songbird" },
  { word: "FIRST", clue: "Foremost" },
  { word: "FISHY", clue: "Suspicious" },
  { word: "FIXED", clue: "Repaired" },
  { word: "FIZZY", clue: "Bubbly" },
  { word: "FLAIR", clue: "Stylish talent" },
  { word: "FLAKE", clue: "Snow bit" },
  { word: "FLAME", clue: "Fire tongue" },
  { word: "FLANK", clue: "Side" },
  { word: "FLARE", clue: "Signal light" },
  { word: "FLASH", clue: "Sudden light" },
  { word: "FLASK", clue: "Pocket bottle" },
  { word: "FLEET", clue: "Group of ships" },
  { word: "FLESH", clue: "Body tissue" },
  { word: "FLICK", clue: "Movie, slang" },
  { word: "FLIER", clue: "Aviator" },
  { word: "FLING", clue: "Throw" },
  { word: "FLINT", clue: "Spark stone" },
  { word: "FLIRT", clue: "Tease romantically" },
  { word: "FLOAT", clue: "Stay on water" },
  { word: "FLOCK", clue: "Group of birds" },
  { word: "FLOOD", clue: "Overflow of water" },
  { word: "FLOOR", clue: "Room bottom" },
  { word: "FLORA", clue: "Plant life" },
  { word: "FLOSS", clue: "Dental string" },
  { word: "FLOUR", clue: "Baking powder base" },
  { word: "FLOWN", clue: "Traveled by air" },
  { word: "FLUID", clue: "Liquid" },
  { word: "FLUKE", clue: "Lucky accident" },
  { word: "FLUME", clue: "Water chute" },
  { word: "FLUNG", clue: "Thrown" },
  { word: "FLUNK", clue: "Fail a test" },
  { word: "FLUSH", clue: "Redden" },
  { word: "FLUTE", clue: "Woodwind instrument" },
  { word: "FLYER", clue: "Handbill" },
  { word: "FOAMY", clue: "Full of bubbles" },
  { word: "FOCAL", clue: "At the center" },
  { word: "FOCUS", clue: "Concentrate" },
  { word: "FOGGY", clue: "Misty" },
  { word: "FOLIO", clue: "Large book page" },
  { word: "FORCE", clue: "Power" },
  { word: "FORGE", clue: "Blacksmith's shop" },
  { word: "FORGO", clue: "Do without" },
  { word: "FORTE", clue: "Strong point" },
  { word: "FORTH", clue: "Onward" },
  { word: "FORTY", clue: "Two score" },
  { word: "FORUM", clue: "Public discussion" },
  { word: "FOUND", clue: "Discovered" },
  { word: "FRAME", clue: "Picture border" },
  { word: "FRANK", clue: "Candid" },
  { word: "FRAUD", clue: "Deception" },
  { word: "FREAK", clue: "Odd person" },
  { word: "FREED", clue: "Released" },
  { word: "FRESH", clue: "New" },
  { word: "FRIAR", clue: "Monk" },
  { word: "FRIED", clue: "Cooked in oil" },
  { word: "FRILL", clue: "Decorative trim" },
  { word: "FRISK", clue: "Pat down" },
  { word: "FROST", clue: "Icy coating" },
  { word: "FROWN", clue: "Scowl" },
  { word: "FROZE", clue: "Turned to ice" },
  { word: "FRUIT", clue: "Orchard produce" },
  { word: "FUDGE", clue: "Chocolate candy" },
  { word: "FULLY", clue: "Completely" },
  { word: "FUMED", clue: "Was angry" },
  { word: "FUNGI", clue: "Mushrooms and molds" },
  { word: "FUNNY", clue: "Amusing" },
  { word: "FUROR", clue: "Uproar" },
  { word: "FURRY", clue: "Covered in hair" },
  { word: "FUSED", clue: "Joined by melting" },
  { word: "FUSSY", clue: "Hard to please" },
  { word: "FUZZY", clue: "Soft and indistinct" },
  { word: "GLASS", clue: "Transparent solid" },
  { word: "GLAZE", clue: "Pottery coating" },
  { word: "GLOVE", clue: "Hand covering" },
  { word: "GRILL", clue: "Barbecue" },
  { word: "HINGE", clue: "Door joint" },
  { word: "HINTS", clue: "Subtle clues" },
  { word: "HONEY", clue: "Bee product" },
  { word: "IMACS", clue: "Apple desktops" },
  { word: "INKED", clue: "Written in ink" },
  { word: "JEANS", clue: "Denim pants" },
  { word: "JUICE", clue: "Fruit drink" },
  { word: "KARAT", clue: "The \"K\" in \"24K gold\"" },
  { word: "KNIFE", clue: "Cutting tool" },
  { word: "LATCH", clue: "Door catch" },
  { word: "LATTE", clue: "Milky espresso" },
  { word: "LEVER", clue: "Prying bar" },
  { word: "LOBBY", clue: "Entrance hall" },
  { word: "LUNAR", clue: "Of the moon" },
  { word: "MATCH", clue: "Fire starter" },
  { word: "METAL", clue: "Element class" },
  { word: "MILLE", clue: "A thousand in France" },
  { word: "MOTOR", clue: "Engine" },
  { word: "MOUSE", clue: "Pointing device" },
  { word: "MUSIC", clue: "Organized sound" },
  { word: "NAILS", clue: "Hammered fasteners" },
  { word: "OPERA", clue: "Sung drama" },
  { word: "OPRAH", clue: "Media mogul Winfrey" },
  { word: "ORBIT", clue: "Path around a planet" },
  { word: "ORGAN", clue: "Pipe instrument" },
  { word: "OSAGE", clue: "Missouri River tributary" },
  { word: "PAINT", clue: "Pigmented liquid" },
  { word: "PANTS", clue: "Trousers" },
  { word: "PAPER", clue: "Writing sheet" },
  { word: "PASTA", clue: "Italian noodles" },
  { word: "PEARL", clue: "Oyster gem" },
  { word: "PEDAL", clue: "Foot lever" },
  { word: "PHONE", clue: "Telephone" },
  { word: "PIANO", clue: "Keyboard instrument" },
  { word: "PIZZA", clue: "Cheese pie" },
  { word: "PLATE", clue: "Dinner dish" },
  { word: "PRINT", clue: "Publish on paper" },
  { word: "RADIO", clue: "Audio broadcast" },
  { word: "ROAST", clue: "Oven-cooked meat" },
  { word: "ROLLE", clue: "Good Times star Esther" },
  { word: "SALES", clue: "Marketer's goal" },
  { word: "SALTY", clue: "Like pretzels" },
  { word: "SCALE", clue: "Musical sequence" },
  { word: "SCARF", clue: "Neck warmer" },
  { word: "SCENE", clue: "Drama segment" },
  { word: "SCENT", clue: "Odor" },
  { word: "SCREW", clue: "Threaded fastener" },
  { word: "SHELF", clue: "Book ledge" },
  { word: "SHIRT", clue: "Upper garment" },
  { word: "SHOES", clue: "Footwear" },
  { word: "SHORE", clue: "Coast" },
  { word: "SKIRT", clue: "Lower garment" },
  { word: "SMOKE", clue: "Fire output" },
  { word: "SOCKS", clue: "Foot coverings" },
  { word: "SOLAR", clue: "Of the sun" },
  { word: "SPARK", clue: "Tiny fire bit" },
  { word: "SPEED", clue: "Drive over the limit" },
  { word: "SPICY", clue: "Hot-flavored" },
  { word: "SPOON", clue: "Soup utensil" },
  { word: "STAGE", clue: "Performance platform" },
  { word: "STEAK", clue: "Beef cut" },
  { word: "STEAM", clue: "Water vapor" },
  { word: "STEEL", clue: "Strong alloy" },
  { word: "STONE", clue: "Rock piece" },
  { word: "STOVE", clue: "Cooking appliance" },
  { word: "SUGAR", clue: "Sweetener" },
  { word: "SUSHI", clue: "Vinegared rice dish" },
  { word: "SWEET", clue: "Sugary" },
  { word: "TABLE", clue: "Dining furniture" },
  { word: "TACOS", clue: "Mexican folds" },
  { word: "TEMPO", clue: "Music speed" },
  { word: "THEME", clue: "Central idea" },
  { word: "TIDAL", clue: "Of the tides" },
  { word: "TITLE", clue: "Name of a work" },
  { word: "TOAST", clue: "Browned bread" },
  { word: "TORCH", clue: "Handheld light" },
  { word: "TOSCA", clue: "Puccini title heroine" },
  { word: "TOWEL", clue: "Drying cloth" },
  { word: "TWIST", clue: "Wind around" },
  { word: "UMAMI", clue: "Savory taste" },
  { word: "VALVE", clue: "Flow control" },
  { word: "WATCH", clue: "Wrist timepiece" },
  { word: "WATER", clue: "H2O" },
  { word: "WHEEL", clue: "Circular roller" },
  { word: "ABSENT", clue: "Not present" },
  { word: "ACROSS", clue: "Horizontal entry" },
  { word: "ACTION", clue: "Deed" },
  { word: "ACTIVE", clue: "Not idle" },
  { word: "ADMIRE", clue: "Regard highly" },
  { word: "ADVICE", clue: "Counsel" },
  { word: "AFFAIR", clue: "Romantic fling" },
  { word: "ALERTS", clue: "Warnings" },
  { word: "ALMOST", clue: "Nearly" },
  { word: "ALWAYS", clue: "At all times" },
  { word: "AMOUNT", clue: "Quantity" },
  { word: "ANIMAL", clue: "Beast" },
  { word: "ANNUAL", clue: "Yearly" },
  { word: "ANSWER", clue: "Solution" },
  { word: "ANYONE", clue: "Any person" },
  { word: "ANYWAY", clue: "Regardless" },
  { word: "APPEAL", clue: "Plead" },
  { word: "APPEAR", clue: "Show up" },
  { word: "AROUND", clue: "Nearby" },
  { word: "ARRIVE", clue: "Get there" },
  { word: "ARTIST", clue: "Creative person" },
  { word: "ASHARP", clue: "Note near B: Hyph.", display: "A-SHARP" },
  { word: "ASSUME", clue: "Take for granted" },
  { word: "ATTACK", clue: "Assault" },
  { word: "ATTEND", clue: "Be present at" },
  { word: "AUTHOR", clue: "Writer" },
  { word: "AVENUE", clue: "Wide street" },
  { word: "BACKED", clue: "Supported" },
  { word: "BAKING", clue: "Oven work" },
  { word: "BALLET", clue: "Dance drama" },
  { word: "BANDIT", clue: "Outlaw" },
  { word: "BANKER", clue: "Finance worker" },
  { word: "BANNER", clue: "Flag-like sign" },
  { word: "BARBER", clue: "Hair cutter" },
  { word: "BARELY", clue: "Only just" },
  { word: "BARREL", clue: "Cask" },
  { word: "BASKET", clue: "Woven container" },
  { word: "BATTLE", clue: "Fight" },
  { word: "BECOME", clue: "Grow to be" },
  { word: "BEFORE", clue: "Prior to" },
  { word: "BEHAVE", clue: "Act properly" },
  { word: "BEHIND", clue: "In back of" },
  { word: "BELIEF", clue: "Conviction" },
  { word: "BELONG", clue: "Be owned by" },
  { word: "BESIDE", clue: "Next to" },
  { word: "BETTER", clue: "Improved" },
  { word: "BEYOND", clue: "Past" },
  { word: "BITTER", clue: "Not sweet" },
  { word: "BOILED", clue: "Cooked in water" },
  { word: "BORDER", clue: "Boundary" },
  { word: "BORROW", clue: "Take temporarily" },
  { word: "BOTTLE", clue: "Glass container" },
  { word: "BRANCH", clue: "Tree limb" },
  { word: "BREATH", clue: "Air from lungs" },
  { word: "BRIDGE", clue: "Span" },
  { word: "BRIGHT", clue: "Shining" },
  { word: "BROKEN", clue: "Shattered" },
  { word: "BRONZE", clue: "Copper-tin alloy" },
  { word: "BUCKET", clue: "Pail" },
  { word: "BUDGET", clue: "Spending plan" },
  { word: "BUFFER", clue: "Cushion" },
  { word: "BULLET", clue: "Cartridge" },
  { word: "BURDEN", clue: "Heavy load" },
  { word: "BUREAU", clue: "Chest of drawers" },
  { word: "BURIED", clue: "Underground" },
  { word: "BUTTER", clue: "Bread spread" },
  { word: "BUTTON", clue: "Clickable disc" },
  { word: "CAMERA", clue: "Photo device" },
  { word: "CANDLE", clue: "Wax light" },
  { word: "CANVAS", clue: "Painting surface" },
  { word: "CANYON", clue: "Deep gorge" },
  { word: "CAREER", clue: "Profession" },
  { word: "CARPET", clue: "Floor covering" },
  { word: "CARROT", clue: "Orange root" },
  { word: "CARVED", clue: "Cut into shape" },
  { word: "CASUAL", clue: "Informal" },
  { word: "CATCHY", clue: "Memorable tune-wise" },
  { word: "CAUGHT", clue: "Captured" },
  { word: "CAUSED", clue: "Brought about" },
  { word: "CAVERN", clue: "Large cave" },
  { word: "CAVIAR", clue: "Fish-egg delicacy" },
  { word: "CAVING", clue: "Spelunking" },
  { word: "CELERY", clue: "Crunchy stalk" },
  { word: "CELLAR", clue: "Basement" },
  { word: "CEMENT", clue: "Building binder" },
  { word: "CENSOR", clue: "Remove content" },
  { word: "CENSUS", clue: "Population count" },
  { word: "CENTER", clue: "Middle" },
  { word: "CEREAL", clue: "Breakfast grain" },
  { word: "CESTLA", clue: "\"That's life\": 2 wds.", display: "C'EST LA" },
  { word: "CHAINS", clue: "Linked metal" },
  { word: "CHAIRS", clue: "Seats" },
  { word: "CHALET", clue: "Alpine cottage" },
  { word: "CHANCE", clue: "Opportunity" },
  { word: "CHANGE", clue: "Alter" },
  { word: "CHARGE", clue: "Ask as price" },
  { word: "CHARMS", clue: "Amulets" },
  { word: "CHARTS", clue: "Graphs" },
  { word: "CHASED", clue: "Pursued" },
  { word: "CHASTE", clue: "Pure" },
  { word: "CHEEKS", clue: "Face sides" },
  { word: "CHEERS", clue: "Toasts" },
  { word: "CHEESE", clue: "Dairy product" },
  { word: "CHERRY", clue: "Red stone fruit" },
  { word: "CHESTS", clue: "Trunks" },
  { word: "CHEWED", clue: "Masticated" },
  { word: "CHICKS", clue: "Baby birds" },
  { word: "CHIEFS", clue: "Leaders" },
  { word: "CHILDS", clue: "Youngster's" },
  { word: "CHILLY", clue: "Coldish" },
  { word: "CHIMES", clue: "Bell sounds" },
  { word: "CHINAS", clue: "Porcelain sets" },
  { word: "CHOICE", clue: "Selection" },
  { word: "CHOKED", clue: "Gagged" },
  { word: "CHOOSE", clue: "Pick" },
  { word: "CHORAL", clue: "Of a choir" },
  { word: "CHORUS", clue: "Refrain" },
  { word: "CHOSEN", clue: "Selected" },
  { word: "CHUCKS", clue: "Throws" },
  { word: "CHUNKY", clue: "Thick pieces" },
  { word: "CHURNS", clue: "Butter makers" },
  { word: "CIPHER", clue: "Coded message" },
  { word: "CIRCLE", clue: "Round figure" },
  { word: "CITIES", clue: "Urban areas" },
  { word: "CITING", clue: "Quoting" },
  { word: "CITRIC", clue: "Like lemons" },
  { word: "CITRON", clue: "Citrus fruit" },
  { word: "CIVICS", clue: "Citizenship study" },
  { word: "CLAIMS", clue: "Asserts" },
  { word: "CLAMOR", clue: "Loud outcry" },
  { word: "CLANGS", clue: "Metallic rings" },
  { word: "CLARET", clue: "Red wine" },
  { word: "CLASPS", clue: "Fasteners" },
  { word: "CLASSY", clue: "Elegant" },
  { word: "CLAUSE", clue: "Contract part" },
  { word: "CLAWED", clue: "Scratched" },
  { word: "CLEAVE", clue: "Split apart" },
  { word: "CLEFTS", clue: "Fissures" },
  { word: "CLENCH", clue: "Tighten fist" },
  { word: "CLEVER", clue: "Smart" },
  { word: "CLICKS", clue: "Mouse sounds" },
  { word: "CLIENT", clue: "Customer" },
  { word: "CLIFFS", clue: "Steep faces" },
  { word: "CLIMAX", clue: "High point" },
  { word: "CLIMBS", clue: "Ascents" },
  { word: "CLINCH", clue: "Settle conclusively" },
  { word: "CLINGS", clue: "Holds tight" },
  { word: "CLINIC", clue: "Medical office" },
  { word: "CLIQUE", clue: "Exclusive group" },
  { word: "CLOCKS", clue: "Timepieces" },
  { word: "CLONED", clue: "Copied genetically" },
  { word: "CLOSED", clue: "Shut" },
  { word: "CLOSER", clue: "Nearer" },
  { word: "CLOSET", clue: "Clothes storage" },
  { word: "CLOTHE", clue: "Dress" },
  { word: "CLOUDS", clue: "Sky fluff" },
  { word: "CLOWNY", clue: "Like a comic" },
  { word: "CLUCKS", clue: "Hen sounds" },
  { word: "CLUMPS", clue: "Clusters" },
  { word: "CLUMSY", clue: "Awkward" },
  { word: "CLUTCH", clue: "Grasp tightly" },
  { word: "COARSE", clue: "Rough" },
  { word: "COASTS", clue: "Shorelines" },
  { word: "COATED", clue: "Covered" },
  { word: "COAXED", clue: "Persuaded gently" },
  { word: "COBALT", clue: "Blue metal" },
  { word: "COBRAS", clue: "Hooded snakes" },
  { word: "COBWEB", clue: "Spider silk" },
  { word: "COCKED", clue: "Tilted" },
  { word: "COCOAS", clue: "Chocolate drinks" },
  { word: "CODDLE", clue: "Pamper" },
  { word: "CODGER", clue: "Old fellow" },
  { word: "CODIFY", clue: "Organize into laws" },
  { word: "COERCE", clue: "Force" },
  { word: "COFFEE", clue: "Morning brew" },
  { word: "COFFIN", clue: "Burial box" },
  { word: "COGENT", clue: "Convincing" },
  { word: "COGNAC", clue: "French brandy" },
  { word: "COHERE", clue: "Stick together" },
  { word: "COILED", clue: "Wound up" },
  { word: "COINED", clue: "Invented a term" },
  { word: "COINER", clue: "Phrase inventor" },
  { word: "COITAL", clue: "Of intercourse" },
  { word: "COLDER", clue: "More chilly" },
  { word: "COLLAR", clue: "Shirt neckband" },
  { word: "COLLIE", clue: "Sheepdog" },
  { word: "COLONY", clue: "Settlement" },
  { word: "COLORS", clue: "Hues" },
  { word: "COLUMN", clue: "Vertical pillar" },
  { word: "COMBAT", clue: "Fighting" },
  { word: "COMEDY", clue: "Funny play" },
  { word: "COMELY", clue: "Attractive" },
  { word: "COMETS", clue: "Tailed sky objects" },
  { word: "COMICS", clue: "Funny papers" },
  { word: "COMING", clue: "Arriving" },
  { word: "COMMIT", clue: "Pledge" },
  { word: "COMMON", clue: "Ordinary" },
  { word: "COMPEL", clue: "Force" },
  { word: "COMPLY", clue: "Obey" },
  { word: "CONCUR", clue: "Agree" },
  { word: "CONDOS", clue: "Apartments" },
  { word: "CONFER", clue: "Consult" },
  { word: "CONFIG", clue: "Setup, briefly" },
  { word: "CONKER", clue: "Horse chestnut" },
  { word: "CONNED", clue: "Swindled" },
  { word: "CONSUL", clue: "Diplomat" },
  { word: "CONTRA", clue: "Against" },
  { word: "CONVEX", clue: "Curved outward" },
  { word: "CONVEY", clue: "Transport" },
  { word: "CONVOY", clue: "Escorted group" },
  { word: "COOKED", clue: "Prepared food" },
  { word: "COOLER", clue: "Less warm" },
  { word: "COOPED", clue: "Confined" },
  { word: "COPIED", clue: "Duplicated" },
  { word: "COPPER", clue: "Reddish metal" },
  { word: "CORALS", clue: "Reef materials" },
  { word: "CORDON", clue: "Police barrier" },
  { word: "CORKED", clue: "Stoppered" },
  { word: "CORNEA", clue: "Eye covering" },
  { word: "CORNED", clue: "___ beef" },
  { word: "CORNER", clue: "Intersection" },
  { word: "CORNET", clue: "Small trumpet" },
  { word: "CORONA", clue: "Solar halo" },
  { word: "CORSET", clue: "Shapewear" },
  { word: "COSMIC", clue: "Of the universe" },
  { word: "COSMOS", clue: "Universe" },
  { word: "COSTLY", clue: "Expensive" },
  { word: "COTTON", clue: "Soft fabric" },
  { word: "COUGAR", clue: "Mountain lion" },
  { word: "COUGHS", clue: "Throat spasms" },
  { word: "COUNTS", clue: "Tallies" },
  { word: "COUNTY", clue: "State division" },
  { word: "COUPLE", clue: "Pair" },
  { word: "COUPON", clue: "Discount slip" },
  { word: "COURSE", clue: "Path of study" },
  { word: "COURTS", clue: "Legal venues" },
  { word: "COUSIN", clue: "Relative" },
  { word: "COVERS", clue: "Lids" },
  { word: "COVERT", clue: "Secret" },
  { word: "COWARD", clue: "Fearful person" },
  { word: "COWBOY", clue: "Ranch hand" },
  { word: "COYOTE", clue: "Prairie wolf" },
  { word: "CRABBY", clue: "Irritable" },
  { word: "CRACKS", clue: "Narrow breaks" },
  { word: "CRADLE", clue: "Baby bed" },
  { word: "CRAFTS", clue: "Handmade arts" },
  { word: "CRAGGY", clue: "Rocky" },
  { word: "CRAMPS", clue: "Muscle spasms" },
  { word: "CRANES", clue: "Tall birds" },
  { word: "CRANKS", clue: "Grouches" },
  { word: "CRASHY", clue: "Like a collision" },
  { word: "CRATER", clue: "Impact hole" },
  { word: "CRAVAT", clue: "Necktie" },
  { word: "CRAVEN", clue: "Cowardly" },
  { word: "CRAVES", clue: "Desires" },
  { word: "CRAWLS", clue: "Moves on knees" },
  { word: "CRAYON", clue: "Colored stick" },
  { word: "CRAZED", clue: "Mad" },
  { word: "CREAKS", clue: "Door sounds" },
  { word: "CREAMS", clue: "Milk fats" },
  { word: "CREASE", clue: "Fold line" },
  { word: "CREATE", clue: "Make" },
  { word: "CREDIT", clue: "Borrowing power" },
  { word: "CREEDS", clue: "Belief systems" },
  { word: "CREEKS", clue: "Small streams" },
  { word: "CREEPS", clue: "Moves stealthily" },
  { word: "CREPES", clue: "Thin pancakes" },
  { word: "CRESTS", clue: "Wave tops" },
  { word: "CREWED", clue: "Staffed a ship" },
  { word: "CRIMES", clue: "Illegal acts" },
  { word: "CRIMPS", clue: "Hair waves" },
  { word: "CRINGE", clue: "Shrink in fear" },
  { word: "CRISES", clue: "Emergencies" },
  { word: "CRISPS", clue: "British chips" },
  { word: "CROAKS", clue: "Frog sounds" },
  { word: "CROCKS", clue: "Earthen pots" },
  { word: "CROCUS", clue: "Spring flower" },
  { word: "CROFTS", clue: "Small farms" },
  { word: "CRONES", clue: "Old women" },
  { word: "CROOKS", clue: "Criminals" },
  { word: "CROONS", clue: "Sings softly" },
  { word: "CROUCH", clue: "Stoop low" },
  { word: "CROWDS", clue: "Large groups" },
  { word: "CROWNS", clue: "Royal headwear" },
  { word: "CRUDDY", clue: "Nasty" },
  { word: "CRUISE", clue: "Pleasure voyage" },
  { word: "CRUMBS", clue: "Bread bits" },
  { word: "CRUMMY", clue: "Lousy" },
  { word: "CRUNCH", clue: "Bite sound" },
  { word: "CRUSTS", clue: "Pie shells" },
  { word: "CRUTCH", clue: "Walking support" },
  { word: "CRYING", clue: "Shedding tears" },
  { word: "CRYPTS", clue: "Underground tombs" },
  { word: "CUBISM", clue: "Art movement" },
  { word: "CUCKOO", clue: "Clock bird" },
  { word: "CUDDLE", clue: "Hold close" },
  { word: "CUDGEL", clue: "Club weapon" },
  { word: "CUEING", clue: "Giving signals" },
  { word: "CUFFED", clue: "Handcuffed" },
  { word: "CULLED", clue: "Selected out" },
  { word: "CUMBER", clue: "Burden" },
  { word: "CUPOLA", clue: "Domed roof" },
  { word: "CURATE", clue: "Museum keeper" },
  { word: "CURBED", clue: "Restrained" },
  { word: "CURDLY", clue: "Like spoiled milk" },
  { word: "CURFEW", clue: "Nighttime limit" },
  { word: "CURING", clue: "Preserving" },
  { word: "CURIOS", clue: "Oddities" },
  { word: "CURLED", clue: "Spiraled" },
  { word: "CURLEW", clue: "Shorebird" },
  { word: "CURVED", clue: "Bent" },
  { word: "CUSTOM", clue: "Usual practice" },
  { word: "CUTEST", clue: "Most adorable" },
  { word: "CUTOFF", clue: "Stopping point" },
  { word: "CUTOUT", clue: "Silhouette" },
  { word: "CUTTER", clue: "Cutting tool" },
  { word: "CYBORG", clue: "Part-machine being" },
  { word: "CYCLES", clue: "Repeating series" },
  { word: "CYGNET", clue: "Young swan" },
  { word: "CYMBAL", clue: "Percussion disc" },
  { word: "CYNICS", clue: "Skeptical people" },
  { word: "CYPRES", clue: "Evergreen tree" },
  { word: "DESERT", clue: "Arid region" },
  { word: "DRAWER", clue: "Sliding box" },
  { word: "EDITOR", clue: "Text reviser" },
  { word: "ENCORE", clue: "Repeat performance" },
  { word: "ENGINE", clue: "Power plant" },
  { word: "ERASER", clue: "Pencil undo-er" },
  { word: "FLAVOR", clue: "Taste quality" },
  { word: "FRIDGE", clue: "Refrigerator, briefly" },
  { word: "GRAVEL", clue: "Driveway rock" },
  { word: "GUITAR", clue: "Six-string instrument" },
  { word: "HAMMER", clue: "Pounding tool" },
  { word: "HANDLE", clue: "Grip" },
  { word: "HIDDEN", clue: "Concealed" },
  { word: "INWARD", clue: "Toward the center" },
  { word: "JACKET", clue: "Light coat" },
  { word: "LADDER", clue: "Climbing frame" },
  { word: "LAPTOP", clue: "Portable computer" },
  { word: "LETTER", clue: "Alphabet character" },
  { word: "MELODY", clue: "Musical line" },
  { word: "MIRROR", clue: "Reflective glass" },
  { word: "MORTAR", clue: "Brick binder" },
  { word: "MUSEUM", clue: "Art repository" },
  { word: "MUSSEL", clue: "Dark-shelled mollusk" },
  { word: "NAPKIN", clue: "Lap cloth" },
  { word: "NOCOST", clue: "Free, with \"at\": 2 wds.", display: "NO COST" },
  { word: "NUMBER", clue: "Digit total" },
  { word: "OMEGAS", clue: "Ω Ω Ω Ω Ω Ω" },
  { word: "OTELLO", clue: "Verdi opera with Iago" },
  { word: "PANTRY", clue: "Food closet" },
  { word: "PEBBLE", clue: "Small round stone" },
  { word: "PENCIL", clue: "Writing graphite" },
  { word: "PILLOW", clue: "Head cushion" },
  { word: "PLANET", clue: "Earth, for one" },
  { word: "PLIERS", clue: "Gripping tool" },
  { word: "PULLEY", clue: "Rope wheel" },
  { word: "PUZZLE", clue: "Brainteaser" },
  { word: "RECALL", clue: "Total ___ (Schwarzenegger film)" },
  { word: "RELATE", clue: "Empathize" },
  { word: "RESOLE", clue: "Fix a shoe bottom" },
  { word: "REVEAL", clue: "Make known" },
  { word: "RHYTHM", clue: "Beat pattern" },
  { word: "RUBBER", clue: "Elastic material" },
  { word: "SCREEN", clue: "Display" },
  { word: "SCRIPT", clue: "Play text" },
  { word: "SCULPT", clue: "Carve a figure" },
  { word: "SHEETS", clue: "Bed linens" },
  { word: "SILVER", clue: "White precious metal" },
  { word: "SKETCH", clue: "Quick drawing" },
  { word: "SOCKET", clue: "Outlet" },
  { word: "SOLVED", clue: "Figured out" },
  { word: "SPARSE", clue: "Thinly distributed" },
  { word: "SPIRAL", clue: "Helix shape" },
  { word: "STATUE", clue: "Sculpted figure" },
  { word: "SUMMER", clue: "Vacation time, for many" },
  { word: "SWITCH", clue: "Toggle control" },
  { word: "TABLET", clue: "Touch computer" },
  { word: "TICKET", clue: "Admission pass" },
  { word: "TRIPOD", clue: "Three-legged stand" },
  { word: "VIOLIN", clue: "Bowed instrument" },
  { word: "WINDOW", clue: "Glass opening" },
  { word: "WRENCH", clue: "Turning tool" },
  { word: "ACTRESS", clue: "Female performer" },
  { word: "BLANKET", clue: "Bed cover" },
  { word: "CAMPING", clue: "Outdoor lodging" },
  { word: "CAPABLE", clue: "Able" },
  { word: "CAPITAL", clue: "Top letter form" },
  { word: "CAPTAIN", clue: "Ship commander" },
  { word: "CAPTION", clue: "Photo text" },
  { word: "CAPTURE", clue: "Seize" },
  { word: "CAREFUL", clue: "Cautious" },
  { word: "CHEAPER", clue: "Less costly" },
  { word: "CHEATED", clue: "Acted dishonestly" },
  { word: "CHECKED", clue: "Verified" },
  { word: "CHIPPED", clue: "Nicked" },
  { word: "CHOPPED", clue: "Cut up" },
  { word: "CLAMPED", clue: "Fastened tightly" },
  { word: "CLARITY", clue: "Clearness" },
  { word: "CLASHED", clue: "Conflicted" },
  { word: "CLEANED", clue: "Made tidy" },
  { word: "CLEARER", clue: "More transparent" },
  { word: "CLUBBED", clue: "Hit with a bat" },
  { word: "COLONEL", clue: "Military rank" },
  { word: "COMPOSE", clue: "Create music" },
  { word: "CONCERT", clue: "Live music event" },
  { word: "CONFINE", clue: "Restrict" },
  { word: "CONFIRM", clue: "Verify" },
  { word: "CONFORM", clue: "Comply with norms" },
  { word: "CONICAL", clue: "Cone-shaped" },
  { word: "CONJURE", clue: "Summon by magic" },
  { word: "CORRECT", clue: "Right" },
  { word: "CORRIDA", clue: "Bullfight" },
  { word: "CORRODE", clue: "Wear away" },
  { word: "CORRUPT", clue: "Dishonest" },
  { word: "COUNTER", clue: "Opposite of clockwise" },
  { word: "CRICKET", clue: "Bat-and-ball game" },
  { word: "CRUELER", clue: "More harsh" },
  { word: "CULPRIT", clue: "Guilty party" },
  { word: "CULTURE", clue: "Shared customs" },
  { word: "CUNNING", clue: "Crafty" },
  { word: "CURSORS", clue: "Screen pointers" },
  { word: "CURTAIN", clue: "Window drape" },
  { word: "CUSHION", clue: "Soft pad" },
  { word: "CUSTARD", clue: "Egg dessert" },
  { word: "CYCLONE", clue: "Storm" },
  { word: "DEEPSET", clue: "Recessed, as eyes: Hyph.", display: "DEEP-SET" },
  { word: "DIAMOND", clue: "Hardest gem" },
  { word: "EARRING", clue: "Earlobe jewelry" },
  { word: "EMERALD", clue: "Green gem" },
  { word: "FREEZER", clue: "Cold storage" },
  { word: "GALLERY", clue: "Art display room" },
  { word: "LANTERN", clue: "Portable lamp" },
  { word: "LEATHER", clue: "Tanned hide" },
  { word: "OCONNOR", clue: "Irish singer Sinead" },
  { word: "OUTWARD", clue: "Away from center" },
  { word: "PERFUME", clue: "Fragrance" },
  { word: "PLASTIC", clue: "Synthetic material" },
  { word: "POTTERY", clue: "Clay ware" },
  { word: "PRINTER", clue: "Paper output device" },
  { word: "RAPSTAR", clue: "Megan Thee Stallion or Cardi B, e.g.: 2 wds.", display: "RAP STAR" },
  { word: "SWEATER", clue: "Knit top" },
  { word: "TEALEAF", clue: "Tea plant part", display: "TEA LEAF" },
  { word: "THEATER", clue: "Playhouse" },
  { word: "TRUMPET", clue: "Brass instrument" },
  { word: "APPLAUSE", clue: "Clapping" },
  { word: "BRACELET", clue: "Wrist jewelry" },
  { word: "DIRECTOR", clue: "Film leader" },
  { word: "KEYBOARD", clue: "Typing device" },
  { word: "NECKLACE", clue: "Throat jewelry" },
  { word: "PORTRAIT", clue: "Face painting" },
  { word: "SAPPHIRE", clue: "Blue gem" },
];

/** Uppercase word set for fast membership tests. */
export const WORD_SET = new Set(ENTRIES.map((e) => e.word));

/** Map from word to entry. */
export const ENTRY_BY_WORD = new Map(ENTRIES.map((e) => [e.word, e]));

export function clueFor(word) {
  const entry = ENTRY_BY_WORD.get(word);
  return entry ? entry.clue : `${word.length}-letter word`;
}

export function displayFor(word) {
  const entry = ENTRY_BY_WORD.get(word);
  return entry?.display ?? word;
}
