#!/usr/bin/env bash
# Remove orphaned browser-app directories from a published site tree.
#
# The production deploy publishes with keep_files: true so the preview/
# directory (written by PR preview deploys) survives each push to main. A side
# effect is that a browser app directory removed or renamed in the source tree
# (e.g. linkchat -> webrtc) lingers on gh-pages forever, and because the home
# page is regenerated by scanning the published tree, the stale app keeps
# showing up. This script prunes those orphans so the published set matches the
# source set before the index is regenerated.
#
# An orphan is a top-level directory in <site-dir> that looks like a browser app
# (contains index.html) but has no matching source browser app directory. The
# preview directory and hidden directories are never touched.
#
# Usage:
#   prune-orphaned-apps.sh <site-dir> [source-dir]
#
# <site-dir>    Published site to prune (typically a gh-pages checkout).
# [source-dir]  Repository source tree defining the canonical app set. Defaults
#               to the repo checkout this script lives in.
set -euo pipefail

site_dir="${1:?site directory required}"
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source_dir="${2:-$(cd "$script_dir/../.." && pwd)}"

if [[ ! -d "$site_dir" ]]; then
  echo "Site directory not found: $site_dir" >&2
  exit 1
fi
if [[ ! -d "$source_dir" ]]; then
  echo "Source directory not found: $source_dir" >&2
  exit 1
fi

# Canonical browser apps: non-hidden top-level source dirs with index.html.
declare -A source_apps=()
for dir in "$source_dir"/*/; do
  name="$(basename "$dir")"
  [[ "$name" == .* ]] && continue
  if [[ -f "$dir/index.html" ]]; then
    source_apps["$name"]=1
  fi
done

pruned=0
for dir in "$site_dir"/*/; do
  [[ -d "$dir" ]] || continue
  name="$(basename "$dir")"
  [[ "$name" == .* ]] && continue
  [[ "$name" == "preview" ]] && continue
  # Only prune things that were published as browser apps.
  [[ -f "$dir/index.html" ]] || continue
  if [[ -z "${source_apps[$name]+x}" ]]; then
    echo "Pruning orphaned app: $name"
    rm -rf "$dir"
    pruned=$((pruned + 1))
  fi
done

if ((pruned == 0)); then
  echo "No orphaned apps to prune."
fi
