// Package hostisolation defines the fixed identifiers and on-disk layout shared
// by the unprivileged agent and its narrowly privileged host helpers.
package hostisolation

import (
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"net"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const (
	// FirecrackerVersion is the only VMM/jailer release accepted by production
	// helpers. Both binaries come from the same checksum-verified release archive.
	FirecrackerVersion = "v1.10.1"

	// Snapshot layouts fence Firecracker's embedded paths. Jailed snapshots
	// always contain the fixed paths below; direct snapshots are only for the
	// explicit local/KVM test runtime.
	SnapshotLayoutJailer = "firecracker-jailer-v1"
	SnapshotLayoutDirect = "firecracker-direct-v1"

	JailedKernelPath       = "/vmlinux"
	JailedRootfsPath       = "/rootfs.ext4"
	JailedSnapshotDir      = "/snapshot"
	JailedSnapshotState    = "/snapshot/vm.state"
	JailedSnapshotMemory   = "/snapshot/vm.mem"
	FirecrackerAPISocket   = "/run/firecracker.socket"
	HostRestoreDir         = "restore"
	HostSnapshotDir        = "snap"
	DefaultSandboxIDBase   = uint32(100_000)
	defaultSandboxIDSpan   = uint64(2_000_000_000)
	maxSupportedThirdOctet = 200
)

var vmIDPattern = regexp.MustCompile(`^[0-9a-f]{12}$`)

// ValidateVMID accepts only the deterministic 12-hex identifier generated by
// the agent. It is safe as a jail, cgroup, socket, and work-directory segment.
func ValidateVMID(id string) error {
	if !vmIDPattern.MatchString(id) {
		return fmt.Errorf("invalid VM id %q (want 12 lowercase hex characters)", id)
	}
	return nil
}

// VMIDFromWorkDir validates and extracts an ID from the fixed vm-<id> layout.
func VMIDFromWorkDir(workDir string) (string, error) {
	base := filepath.Base(filepath.Clean(workDir))
	if !strings.HasPrefix(base, "vm-") {
		return "", fmt.Errorf("invalid VM work directory %q", workDir)
	}
	id := strings.TrimPrefix(base, "vm-")
	if err := ValidateVMID(id); err != nil {
		return "", err
	}
	return id, nil
}

// TapName returns the only TAP name a VM may use.
func TapName(vmID string) (string, error) {
	if err := ValidateVMID(vmID); err != nil {
		return "", err
	}
	return "fc-" + vmID, nil
}

// VMIDFromTapName validates a fixed fc-<id> TAP name.
func VMIDFromTapName(name string) (string, error) {
	if !strings.HasPrefix(name, "fc-") {
		return "", fmt.Errorf("invalid TAP name %q", name)
	}
	id := strings.TrimPrefix(name, "fc-")
	want, err := TapName(id)
	if err != nil {
		return "", err
	}
	if name != want {
		return "", fmt.Errorf("invalid TAP name %q", name)
	}
	return id, nil
}

// SandboxID deterministically assigns a high UID/GID to a VM. The VMM helper
// also rejects an active collision, so every concurrently running jail has a
// distinct identity. The TAP helper independently derives the same owner.
func SandboxID(vmID string, base uint32) (uint32, error) {
	if err := ValidateVMID(vmID); err != nil {
		return 0, err
	}
	if base == 0 {
		base = DefaultSandboxIDBase
	}
	if uint64(base)+defaultSandboxIDSpan > uint64(^uint32(0)) {
		return 0, fmt.Errorf("sandbox UID/GID base %d is too high", base)
	}
	sum := sha256.Sum256([]byte(vmID))
	offset := uint64(binary.BigEndian.Uint32(sum[:4])) % defaultSandboxIDSpan
	return base + uint32(offset), nil
}

// ValidateHostIP constrains TAP addressing to <subnet-base>.<1..200>.1/24.
// subnetBase must be two canonical IPv4 octets such as "172.16".
func ValidateHostIP(hostIP, subnetBase string) error {
	baseParts := strings.Split(subnetBase, ".")
	if len(baseParts) != 2 {
		return fmt.Errorf("invalid subnet base %q", subnetBase)
	}
	for _, part := range baseParts {
		n, err := strconv.Atoi(part)
		if err != nil || n < 0 || n > 255 || strconv.Itoa(n) != part {
			return fmt.Errorf("invalid subnet base %q", subnetBase)
		}
	}
	ip := net.ParseIP(hostIP)
	if ip == nil || ip.To4() == nil || ip.String() != hostIP {
		return fmt.Errorf("invalid canonical IPv4 host address %q", hostIP)
	}
	parts := strings.Split(hostIP, ".")
	third, _ := strconv.Atoi(parts[2])
	if parts[0] != baseParts[0] || parts[1] != baseParts[1] ||
		third < 1 || third > maxSupportedThirdOctet || parts[3] != "1" {
		return fmt.Errorf("host address %q is outside %s.<1..%d>.1", hostIP, subnetBase, maxSupportedThirdOctet)
	}
	return nil
}

// WorkRelativePath returns a traversal-free path beneath the helper's
// configured work root. Every optional component must be one safe segment.
func WorkRelativePath(vmID string, elems ...string) (string, error) {
	if err := ValidateVMID(vmID); err != nil {
		return "", err
	}
	for _, elem := range elems {
		if elem == "" || elem == "." || elem == ".." || filepath.Base(elem) != elem {
			return "", fmt.Errorf("invalid fixed work path segment %q", elem)
		}
	}
	all := append([]string{"vm-" + vmID}, elems...)
	return filepath.Join(all...), nil
}
