#!/usr/bin/env bash
# Regenerate examples/*.stl and examples/REPORT.md
#
# Only ships STLs that pass BOTH:
#   - support removability (cleanup OK)
#   - evolution complexity (interesting OK — not a still-life tower after a few turns)
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p examples
CELL=4

# Wipe previous example STLs so rejected demos cannot linger.
rm -f examples/*.stl

TREE_FLAGS=(
  --mode breakaway
  --support-style tree
  --support-cluster 14
  --support-tip-radius 0.12
  --support-tip-height 2.0
  --support-branch-angle 40
  --support-max-tips-per-trunk 6
  --support-safety-factor 3
)

# Candidate soups to try. Formerly shipped "easy" seeds (settle @ gen 2–4) are
# intentionally absent — the complexity gate rejects them.
# Format: seed:density
CANDIDATE_SOUPS=(
  # Best dual-gate near-misses under default removability settle at gen 6–7
  # (still below the default min_active=8 gate). Kept here for experimentation
  # with --min-active-generations 6:
  # 2146:0.09
  # 11887:0.10
  # 10944:0.12
)

generate_one() {
  local seed="$1"
  local density="$2"
  local out="$3"
  local report
  report="$(cargo run --release --quiet -- --pattern soup --seed "$seed" --density "$density" \
    -x 16 -y 16 -z 24 --cell "$CELL" \
    "${TREE_FLAGS[@]}" -o "$out" 2>/dev/null || true)"
  if [[ ! -f "$out" ]]; then
    echo "error: failed to write ${out}" >&2
    return 1
  fi
  if ! grep -q 'cleanup OK' <<<"$report"; then
    echo "reject seed ${seed}: failed removability gate" >&2
    rm -f "$out"
    return 1
  fi
  if grep -q 'HARD TO REMOVE' <<<"$report"; then
    echo "reject seed ${seed}: HARD TO REMOVE" >&2
    rm -f "$out"
    return 1
  fi
  if ! grep -q 'interesting OK' <<<"$report"; then
    echo "reject seed ${seed}: failed complexity gate" >&2
    rm -f "$out"
    return 1
  fi
  if grep -q 'TOO BORING' <<<"$report"; then
    echo "reject seed ${seed}: TOO BORING" >&2
    rm -f "$out"
    return 1
  fi
  printf '%s\n' "$report"
}

{
  echo "# Example printability reports"
  echo
  echo "Generated by \`./generate-examples.sh\` with \`--cell ${CELL}\`."
  echo
  echo "Only examples that pass **both** gates are shipped:"
  echo
  echo "- **support removability** (\`cleanup OK\`: no rest-on-model, no trapped trunks, score ≥ 70)"
  echo "- **evolution complexity** (\`interesting OK\`: not a still life / short oscillator before generation ≥ 8, i.e. ~⅓ of a 24-gen stack)"
  echo
  echo "Survey note (16×16×24 tree supports, default gates): among 50k seeds at"
  echo "densities 0.08–0.12, **zero** soups pass both gates. Seeds that stay"
  echo "active until generation ≥ 8 always pick up at least one rest-on-model"
  echo "landing under the current support router (typical near-miss score 75)."
  echo "Glider / LWSS / R-pentomino are interesting but fail removability hard"
  echo "(many rest-on-model branches). Formerly shipped \`soup-easy-*\` examples"
  echo "all settle by generation 4 and are rejected by the complexity gate."
  echo
  echo "No STL examples are shipped until removability is relaxed or the"
  echo "support router improves for long-lived soups."
  echo

  shipped=0
  if ((${#CANDIDATE_SOUPS[@]} > 0)); then
    echo "## Candidate soups that passed both gates"
    echo
    for entry in "${CANDIDATE_SOUPS[@]}"; do
      seed="${entry%%:*}"
      density="${entry##*:}"
      out="examples/soup-interesting-${seed}.stl"
      echo "Trying seed=${seed} density=${density}…" >&2
      if report="$(generate_one "$seed" "$density" "$out")"; then
        shipped=$((shipped + 1))
        echo "### soup seed=${seed} density=${density}"
        echo '```'
        echo "$report"
        echo '```'
        echo
      fi
    done
  fi

  if [[ "$shipped" -eq 0 ]]; then
    echo "## Shipped examples"
    echo
    echo "_None._ Dual-gate search found no workable soups under current defaults."
    echo
  fi

} | tee examples/REPORT.md

rm -f /tmp/life-stl-discard.stl
shopt -s nullglob
stls=(examples/*.stl)
echo "Wrote examples/REPORT.md (${#stls[@]} STL files)"
