#!/usr/bin/env bash
# Regenerate examples/*.stl and examples/REPORT.md
#
# Every shipped STL must pass BOTH gates:
#   - evolution complexity (interesting OK — not a still-life tower after a few turns)
#   - cleanup: gusset mode has nothing to remove; breakaway must be cleanup OK
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p examples
CELL=4

# Wipe previous example STLs so rejected demos cannot linger.
rm -f examples/*.stl

run() {
  # run <outfile> <args...> → prints report; fails if gates fail.
  local out="$1"
  shift
  local report
  report="$(cargo run --release --quiet -- "$@" --cell "$CELL" -o "$out" 2>/dev/null || true)"
  if [[ ! -f "$out" ]]; then
    echo "error: failed to write ${out}" >&2
    return 1
  fi
  if grep -q 'TOO BORING' <<<"$report" || ! grep -q 'interesting OK' <<<"$report"; then
    echo "reject ${out}: failed complexity gate" >&2
    rm -f "$out"
    return 1
  fi
  if grep -q 'HARD TO REMOVE' <<<"$report"; then
    echo "reject ${out}: HARD TO REMOVE" >&2
    rm -f "$out"
    return 1
  fi
  # Gusset reports have no removal line (nothing to remove); breakaway must say cleanup OK.
  if grep -q 'breakaway supports:' <<<"$report" && ! grep -q 'cleanup OK' <<<"$report"; then
    echo "reject ${out}: failed removability gate" >&2
    rm -f "$out"
    return 1
  fi
  printf '%s\n' "$report"
}

section() {
  local title="$1"
  shift
  local out="$1"
  shift
  echo "Generating ${out}…" >&2
  local report
  report="$(run "$out" "$@")"
  echo "### ${title}"
  echo '```'
  echo "$report"
  echo '```'
  echo
}

TREE_FLAGS=(
  --mode breakaway
  --support-style tree
  --support-cluster 14
  --support-tip-radius 0.12
  --support-tip-height 2.0
  --support-branch-angle 40
  --support-max-tips-per-trunk 6
  --support-safety-factor 3
)

{
  echo "# Example printability reports"
  echo
  echo "Generated by \`./generate-examples.sh\` with \`--cell ${CELL}\` (A1 Mini: 180×180×180 mm)."
  echo
  echo "Two ways to pass the gates:"
  echo
  echo "- **Gusset mode** (default): every Life birth leans on its three B3 parents"
  echo "  via small diagonal braces — the whole stack is self-supporting, one piece,"
  echo "  nothing to remove. Any interesting pattern qualifies, including gliders."
  echo "- **Breakaway trees** (relaxed): rest-on-model landings are double-tapered"
  echo "  needles now, and up to 2 are allowed — long-lived soups pass again."
  echo
  echo "All examples must be \`interesting OK\` (no still life / short oscillator"
  echo "before generation ≥ max(8, ⅓·depth))."
  echo

  echo "## Gusset (self-supporting causality braces)"
  echo

  section "Glider tower — 64×64×180 mm" examples/gusset-glider-tower.stl \
    --pattern glider -x 16 -y 16 -z 44 --mode gusset

  section "LWSS spaceship — 120×64×180 mm" examples/gusset-lwss.stl \
    --pattern lwss -x 30 -y 16 -z 44 --mode gusset

  section "R-pentomino — 128×128×180 mm" examples/gusset-rpento.stl \
    --pattern rpento -x 32 -y 32 -z 44 --mode gusset

  section "Soup — 96×96×148 mm" examples/gusset-soup-mid.stl \
    --pattern soup --seed 0 --density 0.18 -x 24 -y 24 -z 36 --mode gusset

  section "Soup, A1 Mini max — 176×176×180 mm" examples/gusset-soup-a1max.stl \
    --pattern soup --seed 0 --density 0.16 -x 44 -y 44 -z 44 --mode gusset

  echo "## Breakaway trees (relaxed rest-on-model, double-tapered)"
  echo

  section "Soup seed=29636 — active to gen 8, one rest-on-model" examples/tree-soup-29636.stl \
    --pattern soup --seed 29636 --density 0.08 -x 16 -y 16 -z 24 "${TREE_FLAGS[@]}"

  section "Soup seed=40485 — active to gen 8, one rest-on-model" examples/tree-soup-40485.stl \
    --pattern soup --seed 40485 --density 0.12 -x 16 -y 16 -z 24 "${TREE_FLAGS[@]}"

} | tee examples/REPORT.md

shopt -s nullglob
stls=(examples/*.stl)
ls -lh "${stls[@]}"
echo "Wrote examples/REPORT.md (${#stls[@]} STL files)"
