#!/usr/bin/env bash
# Regenerate examples/*.stl and examples/REPORT.md
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p examples
CELL=4

run() {
  cargo run --release --quiet -- "$@" 2>/dev/null || true
}

capture_report() {
  local label="$1"
  shift
  echo "### ${label}"
  echo '```'
  cargo run --release --quiet -- "$@" 2>/dev/null || true
  echo '```'
  echo
}

{
  echo "# Example printability reports"
  echo
  echo "Generated by \`./generate-examples.sh\` with \`--cell ${CELL}\`."
  echo
  echo "Default supports are **breakaway** (tree/pillar geometry)."
  echo "After snapping them off, Life must be face-connected to the bed (no orphans)."
  echo

  echo "## Still-life garden seed 42 (usually zero supports)"
  echo
  run --quiet --pattern random --seed 42 -x 24 -y 24 -z 48 --cell "$CELL" --mode breakaway \
    -o examples/random-42-breakaway.stl
  capture_report "garden seed=42 / breakaway tree" --pattern random --seed 42 -x 24 -y 24 -z 48 --cell "$CELL" --mode breakaway -o /tmp/life-stl-discard.stl

  echo "## Soup with breakaway tree supports (orphans → not one piece)"
  echo
  run --quiet --pattern soup --seed 99 -x 16 -y 16 -z 24 --cell "$CELL" --mode breakaway \
    --support-style tree --support-radius 0.55 --support-tip-radius 0.3 \
    -o examples/soup-99-breakaway.stl
  capture_report "soup seed=99 / breakaway tree" --pattern soup --seed 99 -x 16 -y 16 -z 24 --cell "$CELL" --mode breakaway \
    --support-style tree --support-radius 0.55 --support-tip-radius 0.3 -o /tmp/life-stl-discard.stl

  echo "## Soup with slim pillars"
  echo
  run --quiet --pattern soup --seed 99 -x 16 -y 16 -z 24 --cell "$CELL" --mode breakaway \
    --support-style pillar --support-radius 0.5 --support-tip-radius 0.28 \
    -o examples/soup-99-pillars.stl
  capture_report "soup seed=99 / breakaway pillars" --pattern soup --seed 99 -x 16 -y 16 -z 24 --cell "$CELL" --mode breakaway \
    --support-style pillar --support-radius 0.5 --support-tip-radius 0.28 -o /tmp/life-stl-discard.stl

  echo "## Glider (orphans)"
  echo
  run --quiet --pattern glider --seed 0 -x 12 -y 12 -z 24 --cell "$CELL" --mode breakaway \
    -o examples/glider-breakaway.stl
  capture_report "glider / breakaway" --pattern glider --seed 0 -x 12 -y 12 -z 24 --cell "$CELL" --mode breakaway -o /tmp/life-stl-discard.stl

  echo "## Tower 10×10×60 cm (still-life garden)"
  echo
  echo "Note: Bambu A1 Mini (180 mm tall) cannot print 600 mm in one piece."
  echo
  run --quiet --pattern random --seed 42 \
    --width-mm 100 --height-mm 100 --depth-mm 600 --cell "$CELL" --mode breakaway \
    -o examples/tower-10x10x60-breakaway.stl
  capture_report "tower 10×10×60 cm / breakaway" --pattern random --seed 42 \
    --width-mm 100 --height-mm 100 --depth-mm 600 --cell "$CELL" --mode breakaway \
    -o /tmp/life-stl-discard.stl

} | tee examples/REPORT.md

rm -f /tmp/life-stl-discard.stl
ls -lh examples/*.stl
echo "Wrote examples/REPORT.md"
