//! Build a binary NVS partition image from a `provisioning.toml` and
//! (optionally) flash it to the device. See `docs/ota.md` for the
//! provisioning + NVS-namespace design.
//!
//! The actual NVS binary format is generated by ESP-IDF's
//! `nvs_partition_gen.py` (already on disk inside `.embuild/`). We just
//! produce the CSV input it expects, then shell out.

use anyhow::{anyhow, bail, Context, Result};
use base64::{engine::general_purpose, Engine as _};
use clap::Parser;
use serde::Deserialize;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Parser)]
#[command(
    version,
    about = "Build + flash NVS partition image from provisioning.toml"
)]
struct Cli {
    /// Path to provisioning.toml.
    #[arg(long, default_value = "provisioning.toml")]
    config: PathBuf,

    /// Where to write the generated NVS .bin.
    #[arg(long, default_value = "target/nvs.bin")]
    out: PathBuf,

    /// NVS partition size in bytes. Must match `partitions.csv` (the `nvs`
    /// row's size column). Default matches the current 0x6000 (24 KB) NVS.
    #[arg(long, default_value_t = 0x6000)]
    nvs_size: u32,

    /// Offset in flash to write to. Must match `partitions.csv` nvs offset.
    #[arg(long, default_value = "0x9000")]
    nvs_offset: String,

    /// If true, also flash the generated image to the device via espflash.
    #[arg(long)]
    flash: bool,

    /// Serial port for flashing.
    #[arg(long, default_value = "/dev/cu.usbserial-0001")]
    port: String,

    /// Path to ESP-IDF's nvs_partition_gen.py. Defaults to the in-repo
    /// embuild copy that gets cloned by `make build`.
    #[arg(
        long,
        default_value = ".embuild/espressif/esp-idf/v5.2.2/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py"
    )]
    nvs_gen: PathBuf,

    /// Path to the python interpreter to run nvs_partition_gen.py with.
    /// Defaults to the embuild-bootstrapped 3.12 venv (matches what the
    /// firmware build uses; ensures script deps are present).
    #[arg(
        long,
        default_value = ".embuild/espressif/python_env/idf5.2_py3.12_env/bin/python"
    )]
    python: PathBuf,

    /// If true, only emit the NVS CSV and identities staging file; do
    /// NOT run nvs_partition_gen.py. Useful for CI parsing checks where
    /// the embuild artifacts aren't installed.
    #[arg(long)]
    dry_run: bool,
}

#[derive(Deserialize, Debug)]
struct ProvisioningConfig {
    wifi: WifiConfig,
    trust: TrustConfig,
    /// Optional. Required by the e-ink SSH firmware, ignored by the original
    /// firmware.
    ssh: Option<SshProvisioningConfig>,
    /// Optional. If absent, the device boots with serial-only logging.
    gcp: Option<GcpConfig>,
    /// Optional. If absent, OTA loop uses its compile-time defaults
    /// (`ghcr.io/imjasonh/esp32:latest`, 60 s poll). All fields are
    /// individually optional too; only present ones override defaults.
    ota: Option<OtaProvisioningConfig>,
}

#[derive(Deserialize, Debug)]
struct WifiConfig {
    ssid: String,
    pass: String,
}

#[derive(Deserialize, Debug)]
struct SshProvisioningConfig {
    host: String,
    #[serde(default = "default_ssh_port")]
    port: u16,
    username: String,
    /// Complete OpenSSH public host key, for example:
    /// `ssh-ed25519 AAAAC3...`.
    host_key: String,
    #[serde(default = "default_ssh_command")]
    command: String,
}

fn default_ssh_port() -> u16 {
    22
}

fn default_ssh_command() -> String {
    "uptime; uname -a".to_string()
}

fn validate_ssh_config(ssh: &SshProvisioningConfig) -> Result<()> {
    if ssh.host.trim().is_empty() || ssh.username.trim().is_empty() {
        bail!("[ssh] host and username must not be empty");
    }
    if ssh.host.len() > 255 {
        bail!("[ssh] host exceeds the 255-byte NVS limit");
    }
    if ssh.username.len() > 31 {
        bail!("[ssh] username exceeds Sunset's 31-byte limit");
    }
    if ssh.port == 0 {
        bail!("[ssh] port must be greater than zero");
    }
    if ssh.command.trim().is_empty() || ssh.command.len() > 511 {
        bail!("[ssh] command must contain 1..=511 bytes");
    }
    Ok(())
}

#[derive(Deserialize, Debug)]
struct TrustConfig {
    identities: Vec<TrustedIdentity>,
    fulcio_root_pem: PathBuf,
    fulcio_intermediate_pem: PathBuf,
}

#[derive(Deserialize, serde::Serialize, Debug)]
struct TrustedIdentity {
    identity: String,
    issuer: String,
}

#[derive(Deserialize, Debug)]
struct GcpConfig {
    project_id: String,
    sa_email: String,
    sa_key_id: String,
    /// Path to a PKCS#8 PEM containing the service account's RSA
    /// private key. Resolved relative to provisioning.toml's directory.
    sa_key_pem: PathBuf,
    /// "trace" / "debug" / "info" / "warn" / "error". Default "info".
    /// Determines the minimum severity that gets shipped to Cloud
    /// Logging (everything still goes to serial).
    #[serde(default = "default_severity")]
    min_severity: String,
    /// Seconds between Cloud Monitoring metric snapshots. Default 300
    /// (5 min). 0 = metrics disabled (cloud_log still runs).
    #[serde(default = "default_metrics_interval")]
    metrics_interval_secs: u32,
}

fn default_severity() -> String {
    "info".to_string()
}

fn default_metrics_interval() -> u32 {
    300
}

#[derive(Deserialize, Debug, Default)]
struct OtaProvisioningConfig {
    /// Override `ghcr.io/<owner>/<name>` repo. Default
    /// `ghcr.io/imjasonh/esp32`.
    repo: Option<String>,
    /// Override the image tag. Default `latest`.
    tag: Option<String>,
    /// Override the OTA poll interval in seconds. Default 60.
    poll_secs: Option<u32>,
}

/// Emit a loud warning if the resolved service-account key path lives
/// inside the repo. It's gitignored by convention but we'd rather
/// flag it explicitly — putting the SA key elsewhere (a `~/.config`
/// location with restricted perms) is the safer default.
fn warn_if_in_repo(sa_key: &Path, repo_dir: &Path) {
    let key = match sa_key.canonicalize() {
        Ok(p) => p,
        // If canonicalize fails the file probably doesn't exist yet;
        // nvs_partition_gen.py will fail loudly on its own.
        Err(_) => return,
    };
    let repo = match repo_dir.canonicalize() {
        Ok(p) => p,
        Err(_) => return,
    };
    if key.starts_with(&repo) {
        tracing::warn!(
            path = %key.display(),
            "sa_key_pem lives inside the repo — keep it gitignored, chmod 600, and consider moving it outside the worktree",
        );
    }
}

fn severity_to_u8(s: &str) -> Result<u8> {
    match s.to_ascii_lowercase().as_str() {
        "trace" => Ok(0),
        "debug" => Ok(1),
        "info" => Ok(2),
        "warn" => Ok(3),
        "error" => Ok(4),
        other => Err(anyhow!("unknown min_severity: {}", other)),
    }
}

fn parse_ed25519_public_key(line: &str) -> Result<[u8; 32]> {
    let mut fields = line.split_whitespace();
    let algorithm = fields.next().ok_or_else(|| anyhow!("host key is empty"))?;
    if algorithm != "ssh-ed25519" {
        bail!("host key algorithm must be ssh-ed25519, got {algorithm}");
    }
    let encoded = fields
        .next()
        .ok_or_else(|| anyhow!("host key is missing its base64 payload"))?;
    let decoded = general_purpose::STANDARD
        .decode(encoded)
        .context("decode host key base64")?;

    let mut cursor = 0;
    let encoded_algorithm = read_ssh_string(&decoded, &mut cursor)?;
    if encoded_algorithm != b"ssh-ed25519" {
        bail!("host key payload says a different algorithm");
    }
    let key = read_ssh_string(&decoded, &mut cursor)?;
    if cursor != decoded.len() {
        bail!("host key payload has trailing data");
    }
    key.try_into()
        .map_err(|_| anyhow!("Ed25519 host key must be 32 bytes, got {}", key.len()))
}

fn read_ssh_string<'a>(input: &'a [u8], cursor: &mut usize) -> Result<&'a [u8]> {
    let length_bytes: [u8; 4] = input
        .get(*cursor..*cursor + 4)
        .ok_or_else(|| anyhow!("truncated SSH string length"))?
        .try_into()
        .unwrap();
    *cursor += 4;
    let length = u32::from_be_bytes(length_bytes) as usize;
    let value = input
        .get(*cursor..*cursor + length)
        .ok_or_else(|| anyhow!("truncated SSH string payload"))?;
    *cursor += length;
    Ok(value)
}

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let args = Cli::parse();

    let toml_str = std::fs::read_to_string(&args.config)
        .with_context(|| format!("read {}", args.config.display()))?;
    let mut cfg: ProvisioningConfig =
        toml::from_str(&toml_str).context("parse provisioning.toml")?;

    // Resolve PEM paths relative to the directory of provisioning.toml,
    // so the user can write `fulcio_root_pem = "trust/fulcio_root.pem"`
    // and it works regardless of where the tool is invoked from.
    let config_dir = args
        .config
        .canonicalize()
        .with_context(|| format!("canonicalize {}", args.config.display()))?
        .parent()
        .ok_or_else(|| anyhow!("no parent dir for {}", args.config.display()))?
        .to_path_buf();
    if cfg.trust.fulcio_root_pem.is_relative() {
        cfg.trust.fulcio_root_pem = config_dir.join(&cfg.trust.fulcio_root_pem);
    }
    if cfg.trust.fulcio_intermediate_pem.is_relative() {
        cfg.trust.fulcio_intermediate_pem = config_dir.join(&cfg.trust.fulcio_intermediate_pem);
    }
    if let Some(gcp) = cfg.gcp.as_mut() {
        if gcp.sa_key_pem.is_relative() {
            gcp.sa_key_pem = config_dir.join(&gcp.sa_key_pem);
        }
        // Validate severity now (before writing CSV) so a typo fails
        // fast with a clear error.
        severity_to_u8(&gcp.min_severity)?;
        // Warn if the SA private key is sitting in the repo directory.
        // It's gitignored by convention (gcp-sa-key.pem) but we'd
        // rather flag it loudly: the operator should keep it
        // somewhere out of the repo and `chmod 600`.
        warn_if_in_repo(&gcp.sa_key_pem, &config_dir);
    }

    tracing::info!(
        identities = cfg.trust.identities.len(),
        ssid = cfg.wifi.ssid,
        ssh = cfg.ssh.is_some(),
        gcp = cfg.gcp.is_some(),
        "loaded provisioning config",
    );

    if !args.dry_run && !args.nvs_gen.exists() {
        bail!(
            "{} not found — run `make build` once so embuild clones ESP-IDF",
            args.nvs_gen.display()
        );
    }

    // Stage the trust/identities JSON to a temp file (nvs_partition_gen
    // reads `binary` values from disk, not stdin).
    let target_dir = args
        .out
        .parent()
        .unwrap_or_else(|| Path::new("target"))
        .to_path_buf();
    std::fs::create_dir_all(&target_dir)
        .with_context(|| format!("create {}", target_dir.display()))?;
    let identities_json_path = target_dir.join("nvs-identities.json");
    let identities_json =
        serde_json::to_vec(&cfg.trust.identities).context("serialize identities")?;
    std::fs::write(&identities_json_path, &identities_json)
        .with_context(|| format!("write {}", identities_json_path.display()))?;
    tracing::info!(
        path = %identities_json_path.display(),
        bytes = identities_json.len(),
        "wrote identities JSON",
    );

    // Store only the raw 32-byte Ed25519 host key in NVS. Parsing the
    // operator-friendly OpenSSH line here keeps the firmware parser small.
    let ssh_host_key_path = if let Some(ssh) = &cfg.ssh {
        validate_ssh_config(ssh)?;
        let host_key = parse_ed25519_public_key(&ssh.host_key)
            .context("parse [ssh].host_key as an OpenSSH Ed25519 public key")?;
        let path = target_dir.join("nvs-ssh-host-key.bin");
        std::fs::write(&path, host_key).with_context(|| format!("write {}", path.display()))?;
        Some(path)
    } else {
        None
    };

    // Build the NVS CSV.
    let csv_path = target_dir.join("nvs.csv");
    write_csv(
        &csv_path,
        &cfg,
        &identities_json_path,
        ssh_host_key_path.as_deref(),
    )
    .context("write NVS CSV")?;
    tracing::info!(path = %csv_path.display(), "wrote NVS CSV");

    if args.dry_run {
        tracing::info!(
            csv = %csv_path.display(),
            "dry-run: skipping nvs_partition_gen.py and flash",
        );
        // Still clean up the identities staging file: it contains the
        // (public) trust identities only, but no need to leave it.
        let _ = std::fs::remove_file(&identities_json_path);
        if let Some(path) = &ssh_host_key_path {
            let _ = std::fs::remove_file(path);
        }
        return Ok(());
    }

    // Run nvs_partition_gen.py.
    let status = Command::new(&args.python)
        .arg(&args.nvs_gen)
        .arg("generate")
        .arg(&csv_path)
        .arg(&args.out)
        .arg(args.nvs_size.to_string())
        .status()
        .with_context(|| format!("run {}", args.nvs_gen.display()))?;
    if !status.success() {
        bail!("nvs_partition_gen.py failed: {}", status);
    }
    let bin_size = std::fs::metadata(&args.out)?.len();
    tracing::info!(
        path = %args.out.display(),
        bytes = bin_size,
        "generated NVS partition image",
    );
    // Clean up staged inputs that are no longer needed. We keep the
    // generated NVS .bin (the user may want to re-flash it) and the
    // CSV (useful for inspection), but the identities JSON is purely
    // an intermediate file.
    let _ = std::fs::remove_file(&identities_json_path);
    if let Some(path) = &ssh_host_key_path {
        let _ = std::fs::remove_file(path);
    }

    if args.flash {
        tracing::info!(
            port = %args.port,
            offset = %args.nvs_offset,
            "flashing NVS image",
        );
        let status = Command::new("espflash")
            .args([
                "write-bin",
                "--port",
                &args.port,
                &args.nvs_offset,
                args.out.to_str().context("non-utf8 out path")?,
            ])
            .status()
            .context("run espflash write-bin")?;
        if !status.success() {
            bail!("espflash write-bin failed: {}", status);
        }
        tracing::info!("NVS partition flashed; reboot the device to pick it up");
    } else {
        tracing::info!(
            "build complete; pass --flash to write to the device, or run `make provision`",
        );
    }

    Ok(())
}

fn write_csv(
    path: &Path,
    cfg: &ProvisioningConfig,
    identities_path: &Path,
    ssh_host_key_path: Option<&Path>,
) -> Result<()> {
    let mut wtr = csv::WriterBuilder::new()
        .quote_style(csv::QuoteStyle::Necessary)
        .from_path(path)?;
    // Header
    wtr.write_record(&["key", "type", "encoding", "value"])?;

    // wifi namespace
    wtr.write_record(&["wifi", "namespace", "", ""])?;
    wtr.write_record(&["ssid", "data", "string", &cfg.wifi.ssid])?;
    wtr.write_record(&["pass", "data", "string", &cfg.wifi.pass])?;

    // ssh namespace (optional). client_seed is intentionally absent: the
    // device creates it after WiFi starts and persists it here at runtime.
    if let (Some(ssh), Some(host_key_path)) = (&cfg.ssh, ssh_host_key_path) {
        wtr.write_record(&["ssh", "namespace", "", ""])?;
        wtr.write_record(&["host", "data", "string", &ssh.host])?;
        wtr.write_record(&["port", "data", "u16", &ssh.port.to_string()])?;
        wtr.write_record(&["username", "data", "string", &ssh.username])?;
        wtr.write_record(&[
            "host_key",
            "file",
            "binary",
            host_key_path
                .to_str()
                .ok_or_else(|| anyhow!("SSH host-key path not UTF-8"))?,
        ])?;
        wtr.write_record(&["command", "data", "string", &ssh.command])?;
    }

    // trust namespace
    wtr.write_record(&["trust", "namespace", "", ""])?;
    wtr.write_record(&[
        "identities",
        "file",
        "binary",
        identities_path
            .to_str()
            .ok_or_else(|| anyhow!("identities path not UTF-8"))?,
    ])?;
    wtr.write_record(&[
        "fulcio_root",
        "file",
        "binary",
        cfg.trust
            .fulcio_root_pem
            .to_str()
            .ok_or_else(|| anyhow!("fulcio_root_pem path not UTF-8"))?,
    ])?;
    wtr.write_record(&[
        "fulcio_inter",
        "file",
        "binary",
        cfg.trust
            .fulcio_intermediate_pem
            .to_str()
            .ok_or_else(|| anyhow!("fulcio_intermediate_pem path not UTF-8"))?,
    ])?;
    // gcp namespace (optional)
    if let Some(gcp) = &cfg.gcp {
        wtr.write_record(&["gcp", "namespace", "", ""])?;
        wtr.write_record(&["project_id", "data", "string", &gcp.project_id])?;
        wtr.write_record(&["sa_email", "data", "string", &gcp.sa_email])?;
        wtr.write_record(&["sa_key_id", "data", "string", &gcp.sa_key_id])?;
        wtr.write_record(&[
            "sa_key_pem",
            "file",
            "binary",
            gcp.sa_key_pem
                .to_str()
                .ok_or_else(|| anyhow!("sa_key_pem path not UTF-8"))?,
        ])?;
        let severity = severity_to_u8(&gcp.min_severity)?;
        wtr.write_record(&["min_severity", "data", "u8", &severity.to_string()])?;
        wtr.write_record(&[
            "metric_intvl",
            "data",
            "u32",
            &gcp.metrics_interval_secs.to_string(),
        ])?;
    }

    // ota namespace (optional). Each field is independently optional;
    // missing keys leave the firmware on its compile-time defaults
    // (`ghcr.io/imjasonh/esp32:latest`, 60 s poll). Key names match
    // src/ota.rs's NVS_REPO / NVS_TAG / NVS_POLL_SECS constants.
    if let Some(ota) = &cfg.ota {
        wtr.write_record(&["ota", "namespace", "", ""])?;
        if let Some(repo) = &ota.repo {
            wtr.write_record(&["repo", "data", "string", repo])?;
        }
        if let Some(tag) = &ota.tag {
            wtr.write_record(&["tag", "data", "string", tag])?;
        }
        if let Some(poll_secs) = ota.poll_secs {
            wtr.write_record(&["poll_secs", "data", "u32", &poll_secs.to_string()])?;
        }
    }

    wtr.flush()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const ED25519_KEY: &str =
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4f test";

    #[test]
    fn parses_openssh_ed25519_host_key() {
        let key = parse_ed25519_public_key(ED25519_KEY).unwrap();
        assert_eq!(key, core::array::from_fn::<_, 32, _>(|index| index as u8));
    }

    #[test]
    fn rejects_other_host_key_algorithms() {
        let error = parse_ed25519_public_key("ssh-rsa AAAA").unwrap_err();
        assert!(error.to_string().contains("must be ssh-ed25519"));
    }

    #[test]
    fn rejects_truncated_host_key() {
        let error = parse_ed25519_public_key("ssh-ed25519 AAAA").unwrap_err();
        assert!(error.to_string().contains("truncated"));
    }

    #[test]
    fn rejects_ssh_username_larger_than_sunset_limit() {
        let config = SshProvisioningConfig {
            host: "server.example.com".into(),
            port: 22,
            username: "x".repeat(32),
            host_key: ED25519_KEY.into(),
            command: "uptime".into(),
        };
        let error = validate_ssh_config(&config).unwrap_err();
        assert!(error.to_string().contains("31-byte"));
    }
}
