package yaml

import (
	"encoding/json"
	"reflect"
	"strings"
	"testing"
)

func mustJSON(t *testing.T, v any) string {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func TestParse(t *testing.T) {
	for _, tc := range []struct {
		name, in, want string
	}{{
		name: "kind kubeconfig",
		in: `apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTg==
    server: https://127.0.0.1:41235
  name: kind-kind
contexts:
- context:
    cluster: kind-kind
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
users:
- name: kind-kind
  user:
    client-certificate-data: Y2VydA==
    client-key-data: a2V5
`,
		want: `{"apiVersion":"v1","clusters":[{"cluster":{"certificate-authority-data":"LS0tLS1CRUdJTg==","server":"https://127.0.0.1:41235"},"name":"kind-kind"}],"contexts":[{"context":{"cluster":"kind-kind","user":"kind-kind"},"name":"kind-kind"}],"current-context":"kind-kind","kind":"Config","preferences":{},"users":[{"name":"kind-kind","user":{"client-certificate-data":"Y2VydA==","client-key-data":"a2V5"}}]}`,
	}, {
		name: "eks exec plugin with env and nested sequence",
		in: `users:
- name: arn:aws:eks:us-west-2:123456789012:cluster/prod
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - prod
      command: aws
      env:
      - name: AWS_PROFILE
        value: "prod"
      interactiveMode: IfAvailable
      provideClusterInfo: false
`,
		want: `{"users":[{"name":"arn:aws:eks:us-west-2:123456789012:cluster/prod","user":{"exec":{"apiVersion":"client.authentication.k8s.io/v1beta1","args":["--region","us-west-2","eks","get-token","--cluster-name","prod"],"command":"aws","env":[{"name":"AWS_PROFILE","value":"prod"}],"interactiveMode":"IfAvailable","provideClusterInfo":false}}}]}`,
	}, {
		name: "gke indented sequences, comments, and null",
		in: `# generated by gcloud
apiVersion: v1
clusters:
  - cluster:
      server: https://34.1.2.3   # public endpoint
    name: gke_proj_us-central1_c1
users:
  - name: gke_proj_us-central1_c1
    user:
      exec:
        command: gke-gcloud-auth-plugin
        env: null
        installHint: 'Install gke-gcloud-auth-plugin for use with kubectl by following
          https://cloud.google.com/blog'
`,
		want: `{"apiVersion":"v1","clusters":[{"cluster":{"server":"https://34.1.2.3"},"name":"gke_proj_us-central1_c1"}],"users":[{"name":"gke_proj_us-central1_c1","user":{"exec":{"command":"gke-gcloud-auth-plugin","env":null,"installHint":"Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog"}}}]}`,
	}, {
		name: "scalars",
		in: `a: true
b: False
c: 42
d: -1.5
e: "true"
f: 'it''s'
g: "tab\tnew\nline \u00e9"
h: ~
i:
j: 0x10
k: yes
l: "# not a comment"
m: a#b
`,
		want: `{"a":true,"b":false,"c":42,"d":-1.5,"e":"true","f":"it's","g":"tab\tnew\nline é","h":null,"i":null,"j":"0x10","k":"yes","l":"# not a comment","m":"a#b"}`,
	}, {
		name: "flow collections",
		in: `a: {x: 1, y: [b, "c, d"], z: {}}
b: [1, 2,
  3]
`,
		want: `{"a":{"x":1,"y":["b","c, d"],"z":{}},"b":[1,2,3]}`,
	}, {
		name: "block scalars",
		in: `lit: |
  line one
    indented
  line three
fold: >-
  folded
  text

  para
keep: |+
  x

after: done
`,
		want: `{"after":"done","fold":"folded text\npara","keep":"x\n\n","lit":"line one\n  indented\nline three\n"}`,
	}, {
		name: "document markers and sequence of sequences",
		in: `---
- - a
  - b
- c
...
`,
		want: `[["a","b"],"c"]`,
	}, {
		name: "quoted keys and empty document",
		in:   `"a b": 1` + "\n" + `'c': 2`,
		want: `{"a b":1,"c":2}`,
	}} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := Parse([]byte(tc.in))
			if err != nil {
				t.Fatalf("Parse: %v", err)
			}
			if s := mustJSON(t, got); s != tc.want {
				t.Errorf("got  %s\nwant %s", s, tc.want)
			}
		})
	}
}

func TestParseEmpty(t *testing.T) {
	for _, in := range []string{"", "\n\n", "# only a comment\n", "---\n"} {
		got, err := Parse([]byte(in))
		if err != nil || got != nil {
			t.Errorf("Parse(%q) = %v, %v; want nil, nil", in, got, err)
		}
	}
}

func TestParseErrors(t *testing.T) {
	for _, in := range []string{
		"a: &anchor 1\nb: *anchor\n",
		"a: !!str 1\n",
		"a: 1\n  b: 2\n",
		"a: 1\na: 2\n",
		"a: \"unterminated\n",
		"a: [1, 2\n",
		"\ta: 1\n",
	} {
		if _, err := Parse([]byte(in)); err == nil {
			t.Errorf("Parse(%q) succeeded, want error", in)
		}
	}
}

func TestUnmarshal(t *testing.T) {
	type exec struct {
		Command string   `json:"command"`
		Args    []string `json:"args"`
	}
	var got struct {
		Insecure bool  `json:"insecure-skip-tls-verify"`
		Port     int   `json:"port"`
		Exec     *exec `json:"exec"`
	}
	in := "insecure-skip-tls-verify: true\nport: 6443\nexec:\n  command: x\n  args: [a, b]\n"
	if err := Unmarshal([]byte(in), &got); err != nil {
		t.Fatal(err)
	}
	if !got.Insecure || got.Port != 6443 || got.Exec == nil || got.Exec.Command != "x" || !reflect.DeepEqual(got.Exec.Args, []string{"a", "b"}) {
		t.Errorf("got %+v", got)
	}
	if err := Unmarshal([]byte("a: [\n"), &got); err == nil || !strings.Contains(err.Error(), "line") {
		t.Errorf("Unmarshal error = %v, want a line number", err)
	}
}
